ENG-120: update wallet connect flow
infinity-keys/ik-landing pull request #107
Opened 2022-06-28 00:27 UTC by stormcloud266

2022-06-28 03:11 UTC, chair28980 requested changes
@stormcloud266 Looking great! Can you also update the text above the button to read:

```
Connect your web3 wallet and sign the message to be part of an early player leaderboard.
```

![image](https://user-images.githubusercontent.com/29414216/176083978-206527a1-8733-4c6b-b289-d356814f1c82.png)

2022-06-28 14:31 UTC, stormcloud266 commented
@chair28980 made the requested update and also changed the button text to "sign message" instead of just "sign"

2022-06-28 21:46 UTC, chair28980 approved these changes

2022-06-29 17:15 UTC, illepic requested changes

2022-06-29 17:15 UTC, illepic commented on components/wallet-email.tsx
> +  const completedClasses = defaultClasses + " line-through";
Let's use `clsx` for this: https://www.npmjs.com/package/clsx. Example: https://github.com/infinity-keys/ik-landing/blob/92b221db1a630d877ecfe9dc947c5b64366c53bf/components/puzzle.tsx#L111

2022-06-29 17:15 UTC, illepic commented on components/wallet.tsx
> +  }, [userAccount, userSignature, setStatus]);
Let's talk about `useEffect` in this context.

2022-07-11 05:27 UTC, illepic requested changes
Just a quick clarification.

2022-07-11 05:27 UTC, illepic commented on components/wallet.tsx
> +    useWalletConnect();
Hell yeah.

2022-07-11 05:27 UTC, illepic commented on components/wallet.tsx
> +            ? "font-bold text-neutral-50"
Did you mean `50` or `500` here?

2022-07-11 05:27 UTC, illepic commented on components/wallet.tsx
> +            ? "font-bold text-neutral-50"
And if you meant `500`, then move `text-neutral-500` to the non-logic styles.

2022-07-11 05:27 UTC, illepic commented on tsconfig.json
> +      "@hooks/*": ["hooks/*"]
💥

2022-07-11 14:39 UTC, stormcloud266 commented on components/wallet.tsx
> +            ? "font-bold text-neutral-50"
I meant `50` just so it's clear what step the user is on

<img width="254" alt="Screen Shot 2022-07-11 at 8 38 34 AM" src="https://user-images.githubusercontent.com/19338130/178290013-a7adca46-1d49-46c8-823e-66d4ba7a2003.png">

2022-07-11 16:48 UTC, illepic approved these changes

2022-07-11 16:48 UTC, merged