embed you tube video on avalanche puzzle landing page
infinity-keys/ik-landing pull request #108
Opened 2022-06-28 20:18 UTC by IvySwing

2022-06-28 21:43 UTC, chair28980 requested changes
Great start! A couple notes.

looks like mobile view is broken


![Screen Shot 2022-06-28 at 5 42 34 PM](https://user-images.githubusercontent.com/29414216/176305105-35937e08-67fa-47c5-b368-c64864419e07.png)

- video is not quite centered on desktop
![video-center](https://user-images.githubusercontent.com/29414216/176305339-4f1e4796-de5d-4426-8f0a-b5d176cea272.png)

2022-06-30 18:31 UTC, IvySwing commented
once review is completed and branch is merged, I will redeploy

2022-06-30 18:59 UTC, stormcloud266 requested changes

2022-06-30 18:59 UTC, stormcloud266 commented on pages/puzzle/[landing].tsx
> +import Video from "public/puzzles/avalanche/video";
Everything is looking super good! The only thing, I don't think we need this import here anymore.

2022-07-01 14:32 UTC, chair28980 commented on pages/puzzle/[landing].tsx
> +import Video from "public/puzzles/avalanche/video";
@IvySwing please get this change in and re-submit for review, should be g2g from there.

2022-07-01 15:22 UTC, IvySwing commented
@chair28980 @stormcloud266 I made the changes and re-requested reviews. Let me know when I can merge

2022-07-01 15:32 UTC, chair28980 approved these changes
Awesome stuff! LGTM! 🍏

2022-07-01 15:35 UTC, stormcloud266 commented
@IvySwing This is looking awesome!

2022-07-01 15:36 UTC, stormcloud266 approved these changes

2022-07-01 16:16 UTC, merged