ENG-1094: orgs for users
infinity-keys/ik-landing pull request #1118
Opened 2024-01-10 19:36 UTC by stormcloud266

- get/create org in service
- create missing orgs on sign up
- update seed user id

2024-01-10 19:45 UTC, illepic requested changes

2024-01-10 19:45 UTC, illepic commented on api/src/functions/auth/auth.ts
> +          name: placeholder,
Just verifying that these are never used as primary key. The DB is creating a cuid for these as primary key right?

2024-01-10 19:45 UTC, illepic commented on scripts/seed.ts
> +      authId: 'user_2amE2mKQHV1MQ0kn15We5aChwqu',
Add us all!

2024-01-10 19:47 UTC, stormcloud266 commented on api/src/functions/auth/auth.ts
> +          name: placeholder,
Yes their ids are all created by the db, just name and slug are also required on orgs

2024-01-10 19:48 UTC, stormcloud266 commented on scripts/seed.ts
> +      authId: 'user_2amE2mKQHV1MQ0kn15We5aChwqu',
All the others are correct, but since I was deleting myself to test the webhook, mine ended up changing

2024-01-11 16:10 UTC, illepic approved these changes

2024-01-11 16:10 UTC, merged