ENG-1103: skip-nft-creation-in-dev-environment
infinity-keys/ik-landing pull request #1127
Opened 2024-01-24 17:40 UTC by stormcloud266

2024-01-24 17:41 UTC, stormcloud266 commented
Current dependencies on/for this PR:
* `main`
  * **PR #951** <a href="https://app.graphite.dev/github/pr/infinity-keys/ik-landing/951?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1126** <a href="https://app.graphite.dev/github/pr/infinity-keys/ik-landing/1126?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1127** <a href="https://app.graphite.dev/github/pr/infinity-keys/ik-landing/1127?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
        * **PR #1128** <a href="https://app.graphite.dev/github/pr/infinity-keys/ik-landing/1128?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #1129** <a href="https://app.graphite.dev/github/pr/infinity-keys/ik-landing/1129?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/infinity-keys/ik-landing/1127?utm_source=stack-comment).

2024-01-29 16:34 UTC, illepic requested changes

2024-01-29 16:34 UTC, illepic commented on api/src/lib/web3/get-nft-data.ts
> +  })
Let's verify that this is actually getting the last. And let's see if Prisma has a `findLast` equivalent.

2024-01-29 16:34 UTC, illepic commented on api/src/lib/web3/get-nft-data.ts
> +  })
Also feel free to throw in more comments about what we're doing here.

2024-01-30 16:23 UTC, illepic approved these changes

2024-02-05 17:05 UTC, stormcloud266 commented
### Merge activity

* **Feb 5, 12:05 PM EST**: @stormcloud266 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/infinity-keys/ik-landing/1127).
* **Feb 5, 12:06 PM EST**: [Graphite](https://app.graphite.dev/github/pr/infinity-keys/ik-landing/1127) rebased this pull request as part of a merge.
* **Feb 5, 12:07 PM EST**: @stormcloud266 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/infinity-keys/ik-landing/1127).

2024-02-05 17:07 UTC, merged