navbar removed from homepage
infinity-keys/ik-landing pull request #1138
Opened 2024-02-19 23:36 UTC by Richard-Burd

The navbar no longer appears on the landing page when a user visits infinitykeys.io.

A "login" button was added to the homepage so users can access the site without needing the navbar's login option.

2024-02-20 15:53 UTC, stormcloud266 requested changes

2024-02-20 15:53 UTC, stormcloud266 commented on web/src/components/Header/Header.tsx
> +  if (pathname === '/') return null
this is perfect

2024-02-20 15:53 UTC, stormcloud266 commented on web/src/pages/HomePage/HomePage.tsx
> +
go ahead and reset this file, we're only going to show login if they navigate away from the home page

2024-02-21 05:27 UTC, Richard-Burd commented
I will close this one and reopen another one with just the Header.tsx being changed...there is no reason to change the Homepage.tsx.  Because this PR was opened before we merged the form into main, this branch is producing merge conflicts that are not worth dealing with whien we just want to add a single line of code to a single file.

2024-02-21 05:27 UTC, closed without merging