Rickaburd/eng 1119 edit button on puzzles
infinity-keys/ik-landing pull request #1146
Opened 2024-02-22 02:39 UTC by Richard-Burd

2024-02-22 15:42 UTC, stormcloud266 requested changes

2024-02-22 15:42 UTC, stormcloud266 commented on web/src/components/RewardablePuzzle/RewardablePuzzle/RewardablePuzzle.tsx
> +  let canEditRewardable = false
Let's do `useState` here instead of a `let`

2024-02-22 15:42 UTC, stormcloud266 commented on web/src/components/RewardablePuzzle/RewardablePuzzle/RewardablePuzzle.tsx
> +  }
Checkout the `onCompleted` callback function that you can use in the `useQuery` hook. You can move this login into that function and it will only run once after it's completed and not on every render. It will look something like this

```
  const { loading } = useQuery<CurrentUserQuery>(CURRENT_USER_QUERY, {
    onCompleted: (data) => {
      // you can move that user org logic here
      console.log(data);
    },
  })
  ```

2024-02-22 23:30 UTC, Richard-Burd commented on web/src/components/RewardablePuzzle/RewardablePuzzle/RewardablePuzzle.tsx
> +  }
Oh Crap, I forgot to do this one! I'll do it and then push again

2024-02-23 14:00 UTC, stormcloud266 approved these changes

2024-02-23 16:08 UTC, merged