ENG-32: web3 minting stuff
infinity-keys/ik-landing pull request #115
Opened 2022-06-30 17:53 UTC by ham-evans

- Added future Mint page, rough minting functionality
- Integrating updated wallet connect package
- setup basic page styles
- add dummy flow
- cleanup conditionals and classes. add secondary button
- Added minter + transaction util, implementing mint functionality
- issues with ending the tx processing circle
- Fixed infinite spinning bugs, added marketplace links
- adding tx messages, connect wallet loading

2022-06-30 18:22 UTC, illepic requested changes

2022-06-30 18:22 UTC, illepic commented on lib/constants.ts
> +export const ETH_RPC =
Move to env var

2022-06-30 18:22 UTC, illepic commented on lib/wallet.ts
> +    chain = (await library.getNetwork()).chainId;
If TS says this could possibly be undefined, try/catch to ensure it always exists.

2022-06-30 18:22 UTC, illepic commented on pages/future/dev/claim-flow.tsx
> +  const openseaLink =
string interpolation instead: ` ${thing}/${blah}`

2022-06-30 18:22 UTC, illepic commented on pages/future/dev/claim-flow.tsx
> +  const [chain, setChain] = useState<number | null>(null);
`undefined` instead of null

2022-06-30 18:22 UTC, illepic commented on pages/future/dev/claim-flow.tsx
> +  const [txMessage, setTxMessage] = useState<string>();
start with `''`

2022-06-30 18:22 UTC, illepic commented on pages/future/dev/minter.tsx
> +  useEffect(() => {
Do all this with just plain ol' TS, no tsx

2022-07-20 17:03 UTC, illepic commented
Noting here that I'm going to bring in the API protection on this work tonight.

2022-07-20 18:42 UTC, stormcloud266 commented
Everything is looking great here. 

I was able to go through the switch and claim flow with Eth, except for finishing the claim since I have no rinkeby bucks.

But for me clicking on "switch to Avalanche" didn't do anything.

Also, I was blocked from hitting the claim page in incognito.

2022-07-22 03:48 UTC, illepic approved these changes

2022-07-22 03:48 UTC, illepic commented on lib/constants.ts
> +  "https://rinkeby.infura.io/v3/c10d222a5bae4a8e97fad0915b06ff5d";
Will b env var for the ID

2022-07-22 03:48 UTC, illepic commented on pages/future/dev/claim-flow.tsx
> +  });
```ts
 const minter = minterUtil({
    updateLoading: (isItLoading) => setIsLoading(isItLoading),
    updateMinted, //etc
    updateTxMessage,
    updateChain,
    puzzleId,
  });
```

2022-07-22 03:48 UTC, illepic commented on lib/wallet.ts
> +        await library.provider.request({
would love it if this did something like 

```ts
chain = await library.provider.request();
```

2022-07-22 03:48 UTC, illepic commented on lib/wallet.ts
> +      } catch (switchError: any) {
we must type this error

2022-07-22 03:48 UTC, illepic commented on lib/wallet.ts
> +      } catch (switchError: any) {
switchError: Web3ChainError

2022-07-22 03:48 UTC, illepic commented on pages/api/future/dev/check-achievement.ts
> +import ContractABI from "../../../future/dev/ContractABI.json";
Let's make new folder called "contracts", then config tsconfig.json at root to `@contracts` alias this.

2022-07-22 03:48 UTC, illepic commented on pages/api/future/dev/check-achievement.ts
> +  let claimed: boolean;
Initiate with `false`, then don't cast.

2022-07-22 03:48 UTC, illepic commented on pages/api/future/dev/check-achievement.ts
> +  let claimed: boolean;
Change path from `future/dev/check-achievement` to `onchain/achievement`

2022-07-22 03:48 UTC, illepic commented on pages/api/future/dev/check-achievement.ts
> +  if (!account || !puzzleId) return res.status(401).end();
500 instead

2022-07-22 03:50 UTC, illepic approved these changes

2022-07-22 03:53 UTC, merged