itsmekori/eng-1133-update-home-page-and-nav (DO NOT MERGE)
infinity-keys/ik-landing pull request #1160
Opened 2024-03-13 17:00 UTC by IvySwing

2024-03-13 18:04 UTC, stormcloud266 commented on web/src/pages/HomePage/HomePage.tsx
> +                {/* <Button round solid onClick={handleScrollToForm}> */}
we can remove this

2024-03-13 18:04 UTC, stormcloud266 commented on web/src/pages/HomePage/HomePage.tsx
> +            {/* <HomeContactForm ref={formRef} /> */}
go ahead and toss this too

2024-03-13 18:04 UTC, stormcloud266 approved these changes

2024-03-14 15:12 UTC, illepic requested changes
See @stormcloud266 's comments

2024-03-14 16:09 UTC, merged