User can see their Puzzles & Packs on Their Profile
infinity-keys/ik-landing pull request #1166
Opened 2024-03-17 22:07 UTC by Richard-Burd

2024-03-17 22:48 UTC, Richard-Burd commented
Am I only able to request a review from one person now?

2024-03-19 14:52 UTC, stormcloud266 requested changes

2024-03-19 14:52 UTC, stormcloud266 commented on api/src/graphql/userRewardables.sdl.ts
> +    id: String!
Let's check if we need to redefine these here or if we can use the ones we already have.

2024-03-19 14:52 UTC, stormcloud266 commented on web/src/components/ProfileCell/ProfileCell.tsx
> +
This can probably be grabbed from autogenerated types

2024-03-19 14:52 UTC, stormcloud266 commented on web/src/components/ProfileCell/ProfileCell.tsx
> +  }
Let's use `useState` instead of the `let` here, and that map functionality can be moved into the `useQuery`'s `onComplete` method

2024-03-19 14:54 UTC, stormcloud266 commented
> Am I only able to request a review from one person now?

Yes that changed after we moved off the paid plan

2024-03-20 15:03 UTC, stormcloud266 approved these changes

2024-03-20 15:03 UTC, merged