Itsmekori/eng 119 test all links on landing page
infinity-keys/ik-landing pull request #138
Opened 2022-07-08 21:34 UTC by IvySwing

2022-07-11 05:18 UTC, illepic requested changes

2022-07-11 05:18 UTC, illepic commented on components/svg/twitter-icon-svg.tsx
> +    >
I didn't notice this before, but let's move the a tag out of the SVG component. Wrap all SVGs with an a tag where they are used instead.

2022-07-11 05:18 UTC, illepic commented on components/header.tsx
>                    <Link href={"/"}>
I know this isn't technically part of these changes, but remove the brackets off this href. Just the double quotes is fine.

2022-07-11 05:18 UTC, illepic commented on cypress/e2e/spec.cy.js
> +    cy.visit("/");
Isn't each of the `cy.visit('/')` redundant in these tests since you already have a `beforeEach()` above that already does this?

2022-07-11 05:18 UTC, illepic commented on cypress/e2e/spec.cy.js
> +    cy.url().should("include", "/puzzles");
If you're testing above with `Cypress.config().baseUrl`, may as well here too.

2022-07-11 05:18 UTC, illepic commented on cypress/e2e/spec.cy.js
> +    cy.get('[data-cy="discord"]').invoke("removeAttr", "target").click();
There may be a Cypress utility already that effectively prevents "open new window" (which I'm assuming removal of the `target` attribute does here)

2022-07-11 17:56 UTC, IvySwing commented on components/header.tsx
>                    <Link href={"/"}>
it's done✔

2022-07-11 18:01 UTC, IvySwing commented on cypress/e2e/spec.cy.js
> +    cy.visit("/");
the beforeEach() isn't needed so I remove it - it doesn't work for all of the tests blocks

2022-07-11 18:54 UTC, IvySwing commented on cypress/e2e/spec.cy.js
> +    cy.get('[data-cy="discord"]').invoke("removeAttr", "target").click();
Yes that is what I'm doing in the above code.  In the docs: https://docs.cypress.io/guides/references/trade-offs#Multiple-tabs - using".invoke" seemed to be the best option.  I checked and didn't see any utilities that would do the same thing.  If you see something, please let me know.

2022-07-12 04:30 UTC, illepic requested changes

2022-07-12 04:30 UTC, illepic commented on components/svg/discord-svg.tsx
> +    rel="noreferrer"
Checking that we're removing the link tag here.

2022-07-12 04:30 UTC, illepic commented on components/svg/twitter-icon-svg.tsx
> +    rel="noreferrer"
Also checking on this one.

2022-07-12 04:30 UTC, illepic commented on cypress/e2e/spec.cy.js
> +const { link } = require("fs");
We probably don't need this.

2022-07-12 04:30 UTC, illepic commented on cypress/e2e/spec.cy.js
> +    cy.visit("/");
Please add the beforeEach back in. It runs prior to each `it()` test (but won't help in this particular test where you route back to / multiple times).

2022-07-12 17:43 UTC, IvySwing commented on cypress/e2e/spec.cy.js
> +const { link } = require("fs");
removed

2022-07-15 15:30 UTC, illepic approved these changes

2022-07-15 15:30 UTC, merged