ENG-148: update puzzles layout
infinity-keys/ik-landing pull request #148
Opened 2022-07-12 17:25 UTC by stormcloud266

Adds support for toggling between a grid or list view on the /puzzles page. Save user's choice to local storage.

2022-07-12 23:44 UTC, chair28980 approved these changes
LGTM 🍏

2022-07-18 18:19 UTC, illepic requested changes

2022-07-18 18:19 UTC, illepic commented on components/puzzle-thumbnail.tsx
> +              size={puzzle.isGrid ? 128 : 56}
How does this look mobile?

2022-07-18 18:19 UTC, illepic commented on pages/puzzles.tsx
> +import { ViewListIcon, ViewGridIcon } from "@heroicons/react/solid";
Can you verify for me if we can do the more modular import, ie 

```ts
import ViewListIcon from "@heroicons/react/solid/ViewListIcon";
```

General named imports will bring in the entire library and I wonder if heroicons allows for this method.

2022-07-18 18:19 UTC, illepic commented on pages/puzzles.tsx
> +  const [isGrid, setIsGrid] = useState<boolean | null>(null);
Any reason to not just initialize as boolean? ie

```ts
const [isGrid, setIsGrid] = useState(false);
```

2022-07-18 18:19 UTC, illepic commented on pages/puzzles.tsx
> +  const setView = ({ gridView }: { gridView: boolean }) => {
Maybe just:

```ts
const setView = (gridView: boolean) => {
```

2022-07-19 15:01 UTC, stormcloud266 commented on components/puzzle-thumbnail.tsx
> +              size={puzzle.isGrid ? 128 : 56}
It looked fine to me using Chrome devices and on my phone.

<img width="267" alt="Screen Shot 2022-07-19 at 8 48 09 AM" src="https://user-images.githubusercontent.com/19338130/179782184-044750a9-2427-44df-bd14-0bbf3df13d0e.png">

2022-07-19 15:09 UTC, stormcloud266 commented on pages/puzzles.tsx
> +  const [isGrid, setIsGrid] = useState<boolean | null>(null);
I show the list when it isn't null because if the initial value is different than the user's saved one, there is a gross jump between the two.

![Jul-19-2022 09-07-58](https://user-images.githubusercontent.com/19338130/179784578-ec4738e4-5ccd-4a39-aab1-8ec44a77f293.gif)

2022-07-19 15:12 UTC, stormcloud266 commented on pages/puzzles.tsx
> +import { ViewListIcon, ViewGridIcon } from "@heroicons/react/solid";
This worked

2022-07-19 16:24 UTC, illepic commented on pages/puzzles.tsx
> +  const [isGrid, setIsGrid] = useState<boolean | null>(null);
Instead of `isGrid`:

```ts
type GridType = 'grid' | 'list' | 'kittens';
```

2022-07-19 16:43 UTC, illepic approved these changes

2022-07-19 16:43 UTC, merged