Itsmekori/eng 142 test all links on puzzle dashboard
infinity-keys/ik-landing pull request #156
Opened 2022-07-14 17:39 UTC by IvySwing

2022-07-18 18:28 UTC, illepic requested changes

2022-07-18 18:28 UTC, illepic commented on pages/puzzle/[landing].tsx
> -          <main className="text-center pt-5">
Why is the classname `input` on the `main` tag here?

2022-07-18 18:37 UTC, IvySwing commented on pages/puzzle/[landing].tsx
> -          <main className="text-center pt-5">
I was testing and playing around and didn't remove my notes. Thanks for the catch! I'll remove it.

2022-07-20 18:37 UTC, illepic requested changes
Only 2 small things!

2022-07-20 18:37 UTC, illepic commented on cypress/e2e/puzzle.cy.js
> +    // cy.visit("/");
let's nuke the commented out cy.visit()s

2022-07-20 18:37 UTC, illepic commented on components/header.tsx
> +                        <a className="link text-2xl font-medium hover:text-turquoise">
Let's change this class to something like `header-nav--link` (BEM syntax) so that way we don't collide with the inevitable `.link` class that could should up elsewhere.

2022-07-20 18:39 UTC, IvySwing commented on cypress/e2e/puzzle.cy.js
> +    // cy.visit("/");
I'm going to do cleanup after I create the last few tests.  I mark them as comments to know what I need to delete.

2022-07-20 18:40 UTC, IvySwing commented on components/header.tsx
> +                        <a className="link text-2xl font-medium hover:text-turquoise">
it's done!

2022-07-22 20:17 UTC, illepic approved these changes

2022-07-22 20:17 UTC, merged