ham/eng 156 metadata api
infinity-keys/ik-landing pull request #157
Opened 2022-07-14 18:52 UTC by ham-evans

- metadata api and metadata json
- updating metadata

2022-07-20 18:45 UTC, stormcloud266 approved these changes
Everything is looking good to me

2022-07-22 16:04 UTC, illepic requested changes

2022-07-22 16:04 UTC, illepic commented on pages/api/metadata/ikachievement.ts
> +  if (!tokenid || typeof tokenid === "object") return res.status(500).end();
Change this to !== string

2022-07-22 16:04 UTC, illepic commented on pages/api/metadata/ikachievement.ts
> +  res.status(200).json(metadata[tokenId]);
Just `res.json(metadata[tokenId])`

2022-07-22 16:20 UTC, illepic commented
Also tsconfig conflict, easy fix.

2022-07-27 21:33 UTC, illepic approved these changes

2022-07-27 21:34 UTC, merged