ENG-149: update puzzles to include pagination
infinity-keys/ik-landing pull request #160
Opened 2022-07-18 15:52 UTC by stormcloud266

Adds pagination and 'puzzles per page' select on /puzzles

2022-07-19 20:56 UTC, illepic requested changes

2022-07-19 20:56 UTC, illepic commented on components/puzzles/dropdown.tsx
> +                      href={count === 8 ? "/puzzles" : `/puzzles/${count}/1`}
Instead of magic `8` here: 

```ts
const [ smallestPaginationCount ] = PAGINATION_COUNTS;
```

2022-07-19 20:56 UTC, illepic commented on components/puzzles/dropdown.tsx
> +import { Menu, Transition } from "@headlessui/react";
Hell yes.

2022-07-19 20:56 UTC, illepic commented on components/puzzles/layout-buttons.tsx
> +      <PuzzlesDropdown currentCount={puzzlesCount || 8} />
Use the constant here again

2022-07-19 20:56 UTC, illepic commented on components/puzzles/layout.tsx
> +}
With the reuse of this, we may as well move it to `@lib/types`!

2022-07-19 20:56 UTC, illepic commented on components/puzzles/layout.tsx
> +  const [layout, setLayout] = useState<GridType>(GridType.Unknown);
NICE

2022-07-19 20:56 UTC, illepic commented on components/puzzles/layout.tsx
> +  const [count, page] = query.puzzlesArgs || ["8", "1"];
Another magic 8

2022-07-19 20:56 UTC, illepic commented on components/puzzles/pagination.tsx
> +  const toDefaultPage = puzzlesCount === 8 && pageNum === 2;
Why 2 for default page? Also, magic 8.

2022-07-19 20:56 UTC, illepic commented on tsconfig.json
> +    "downlevelIteration": true,
Why do we need this? We don't transpile to ES5.

2022-07-19 20:57 UTC, illepic commented
Noting here that the grid started in list mode for me on a fresh link

2022-07-20 15:35 UTC, stormcloud266 commented on components/puzzles/pagination.tsx
> +  const toDefaultPage = puzzlesCount === 8 && pageNum === 2;
It's going 'to' the default page `/puzzles` if you are on page 2 and hit the previous button.

2022-07-20 15:43 UTC, stormcloud266 commented on tsconfig.json
> +    "downlevelIteration": true,
The target in the tsconfig is "es5" so when I create an array from the number of pages in getStaticPaths `[...Array(numOfPages).keys()].map` it gives an error. The downlevelIteration removes the error but so does changing the target to "es6"

2022-07-20 16:11 UTC, illepic requested changes

2022-07-20 16:11 UTC, illepic commented on components/puzzles/layout.tsx
> +};
Just pull on our guy here https://lodash.com/docs/4.17.15#toNumber

```ts
import toNumber from 'lodash/toNumber';
```

2022-07-20 16:18 UTC, illepic approved these changes

2022-07-20 16:19 UTC, merged