header footer every page, fixing height issues
infinity-keys/ik-landing pull request #180
Opened 2022-07-22 19:00 UTC by ham-evans

2022-07-22 21:39 UTC, stormcloud266 requested changes

2022-07-22 21:39 UTC, stormcloud266 commented on components/puzzle.tsx
> +        // adding padding and margin to make loading ball same height as
This looks awesome on desktop but it's a bit too big on mobile

2022-07-22 21:39 UTC, stormcloud266 commented on pages/claim/[puzzleName].tsx
> +        <div className="radial-bg min-h-[calc(100vh-80px)] flex items-center">
This makes it look way better!

2022-07-27 21:49 UTC, illepic requested changes
Move header/footer to Wrapper and adjust so each page gets what it needs.

2022-08-01 16:19 UTC, illepic approved these changes

2022-08-01 16:33 UTC, merged