ENG-182: add starter pack page UI
infinity-keys/ik-landing pull request #187
Opened 2022-07-25 01:37 UTC by stormcloud266

2022-07-25 19:36 UTC, chair28980 approved these changes
UI layout LGTM 🍏

2022-07-28 20:52 UTC, illepic commented on pages/pack/[packName].tsx
> +
We gotta get this out to a shared ts interface in `types.ts` soon.

2022-07-28 20:53 UTC, illepic requested changes

2022-07-28 20:53 UTC, illepic commented on pages/pack/[packName].tsx
> +          <div className={clsx({ "opacity-0": width === 0 })}>
What's going on here?

2022-07-28 20:59 UTC, stormcloud266 commented on pages/pack/[packName].tsx
> +          <div className={clsx({ "opacity-0": width === 0 })}>
at the very beginning of the page load, before it gets the window width, it will be set to list view (since width will be at 0) and then it will pop into the grid view and shift the layout on desktop.

2022-07-29 05:04 UTC, illepic approved these changes

2022-07-29 17:40 UTC, merged