ENG-184: add-buttons-to-starter-pack-in-header
infinity-keys/ik-landing pull request #196
Opened 2022-07-29 16:07 UTC by stormcloud266

* Adds button link to the starter pack page in the header
* Adds xs media query
* Makes a few minor style changes to header

![nav](https://user-images.githubusercontent.com/19338130/181799115-91594ea0-95c7-4233-a201-f953495e6f86.gif)

2022-07-29 23:53 UTC, chair28980 approved these changes
LGTM 🍀

2022-07-31 05:37 UTC, illepic requested changes

2022-07-31 05:37 UTC, illepic commented on components/footer.tsx
> +          <div className="w-full py-6 flex flex-col sm:flex-row items-center justify-center border-b border-indigo-500 lg:border-none">
Instead of 
```ts
flex flex-col sm:flex-row
```
just do
```ts
// remove flex and flex-row
sm:flex 
```

2022-07-31 05:37 UTC, illepic commented on components/footer.tsx
> +            <Link href="/pack/starter-pack">
Any chance we can use the new `Button` component with one of its variants?

2022-07-31 05:37 UTC, illepic commented on components/header.tsx
> +                <PuzzleButton />
I don't think this is `PuzzleButton` any longer with @IvySwing 's work.

2022-07-31 05:37 UTC, illepic commented on components/header.tsx
> +                <a className="hover:bg-turquoise py-2 px-4 border-2 border-turquoise hover:border-white rounded-md text-xl font-medium text-white hover:text-blue box-border inline-block xs:hidden">
If this is "hidden at small", just make it `hidden sm:inline-block` (this instead becomes "start out hidden, show at breakpoint"

2022-07-31 05:37 UTC, illepic commented on components/header.tsx
> +                  <a className="mr-4 hover:bg-turquoise py-2 px-4 border-2 border-turquoise hover:border-white rounded-md text-xl font-medium text-white hover:text-blue box-border hidden xs:inline-bl
Why xs?

2022-07-31 05:37 UTC, illepic commented on tailwind.config.js
> +      xs: "475px",
Why xs?

2022-07-31 05:37 UTC, illepic commented on tailwind.config.js
> +      xs: "475px",
And if we need to add things like `screens`, add to `extend` section below, then you won't have to import `defaultTheme`.

2022-07-31 05:39 UTC, illepic commented
Also, pull in latest `main` branch to fix conflicts.

2022-07-31 14:09 UTC, stormcloud266 commented on components/footer.tsx
> +            <Link href="/pack/starter-pack">
Will update soon

2022-07-31 14:15 UTC, stormcloud266 commented on components/header.tsx
> +                <a className="hover:bg-turquoise py-2 px-4 border-2 border-turquoise hover:border-white rounded-md text-xl font-medium text-white hover:text-blue box-border inline-block xs:hidden">
This needs to start out visible and then be hidden on xs and larger. It's for the button in the dropdown nav before it can fit into the nav bar.

2022-07-31 14:16 UTC, stormcloud266 commented on components/header.tsx
> +                  <a className="mr-4 hover:bg-turquoise py-2 px-4 border-2 border-turquoise hover:border-white rounded-md text-xl font-medium text-white hover:text-blue box-border hidden xs:inline-bl
They wanted to call attention to the starter pack button, so I added the xs breakpoint to be able to keep it in the nav bar as long as possible. It just seemed like using sm left a lot of empty space where the button could be.

2022-07-31 14:16 UTC, stormcloud266 commented on tailwind.config.js
> +      xs: "475px",
According to their docs, the smaller breakpoints need to be added this way to keep the correct order.
https://tailwindcss.com/docs/screens#adding-smaller-breakpoints

2022-07-31 14:21 UTC, stormcloud266 commented on components/footer.tsx
> +          <div className="w-full py-6 flex flex-col sm:flex-row items-center justify-center border-b border-indigo-500 lg:border-none">
The flex-col keeps the items centered when stacked vertically on screens below sm

<img width="367" alt="Screen Shot 2022-07-31 at 8 19 51 AM" src="https://user-images.githubusercontent.com/19338130/182030718-94eb43ba-f053-42f7-a24b-1504874fb20c.png">

2022-07-31 14:49 UTC, stormcloud266 commented on components/footer.tsx
> +            <Link href="/pack/starter-pack">
Looks like the variations are for text color and width, what if I start a new PR that adds 'secondary styles' to the button component and then replace both these links and buttons in the claim page since they are very similar?

2022-07-31 17:00 UTC, illepic commented on components/header.tsx
> +                <a className="hover:bg-turquoise py-2 px-4 border-2 border-turquoise hover:border-white rounded-md text-xl font-medium text-white hover:text-blue box-border inline-block xs:hidden">
Can we make this `sm` instead? There's a reason that tailwind doesn't differentiate between all the various "mobile" sizes: there's just "mobile" and then "everything after".

2022-07-31 17:02 UTC, illepic commented on components/header.tsx
> +                <a className="hover:bg-turquoise py-2 px-4 border-2 border-turquoise hover:border-white rounded-md text-xl font-medium text-white hover:text-blue box-border inline-block xs:hidden">
Noting here that what we see as a lot of space is because we're grabbing and resizing our window constantly. A user on a phone or desktop won't be doing that.

2022-07-31 17:04 UTC, illepic commented on components/footer.tsx
> +            <Link href="/pack/starter-pack">
Perfect.

2022-07-31 22:57 UTC, merged