ENG-183: add starter pack check wallet flow
infinity-keys/ik-landing pull request #197
Opened 2022-07-29 17:41 UTC by stormcloud266

Adds starter pack minting functionality

2022-07-31 22:19 UTC, illepic commented on pages/claim/[puzzleName].tsx
> +  const verify = async (account: string, tokenId: number, chain: number) => {
We gotta tune this up soon.

2022-07-31 22:20 UTC, illepic commented on pages/pack/[packName].tsx
> +  const [loading, setLoading] = useState<boolean>(false);
We absolutely have to move this to xstate next.

2022-07-31 22:23 UTC, illepic requested changes

2022-07-31 22:23 UTC, illepic commented on pages/pack/[packName].tsx
> +  // };
Nuke commented out code.

2022-07-31 22:23 UTC, illepic commented on pages/pack/[packName].tsx
> +                        }${nftId}`}
we gotta turn this into a helper function, but can later

2022-07-31 23:08 UTC, illepic approved these changes

2022-08-01 01:37 UTC, chair28980 approved these changes
LGTM 🍏

2022-08-01 01:37 UTC, merged