ENG-210: in-puzzles-grid-use-the-cloudinary
infinity-keys/ik-landing pull request #214
Opened 2022-08-03 20:20 UTC by stormcloud266

- add cloudinary to graphql queries
- use nft image in grid

2022-08-03 21:53 UTC, chair28980 approved these changes
UI LGTM! 🍏

2022-08-04 19:36 UTC, illepic requested changes

2022-08-04 19:36 UTC, illepic commented on components/cloud-image.tsx
> +      quality={100}
What sizes savings do we see when fiddling with this?

2022-08-04 20:30 UTC, illepic approved these changes

2022-08-04 20:30 UTC, merged