ENG-240: puzzle-grid-nft-image-zoom
infinity-keys/ik-landing pull request #219
Opened 2022-08-04 21:35 UTC by stormcloud266

makes round images more rounder

2022-08-04 22:20 UTC, illepic requested changes

2022-08-04 22:20 UTC, illepic commented on styles/globals.css
> +}
There's a reason that span isn't block. What do we need this for?

2022-08-04 22:35 UTC, stormcloud266 commented on styles/globals.css
> +}
It's oval instead of round without it

2022-08-04 23:26 UTC, stormcloud266 commented on styles/globals.css
> +}
I can also get rid of the ovalness of inline-block using absolute on my inner div if that is a better approach. no block override

2022-08-05 05:53 UTC, illepic commented on styles/globals.css
> +}
Let me mess with some Next Image attributes here to see what we can do.

2022-08-06 06:25 UTC, illepic approved these changes

2022-08-06 06:26 UTC, merged