ENG-277: create packs page
infinity-keys/ik-landing pull request #258
Opened 2022-08-17 17:56 UTC by stormcloud266

Adds packs collection page. Updates puzzle components to be used with packs. Add packs link to header.

2022-08-18 13:22 UTC, chair28980 approved these changes
The UI lgtm! 🍏

2022-08-23 04:37 UTC, illepic requested changes
The only thing here is to try zod.

2022-08-23 04:37 UTC, illepic commented on lib/utils.ts
> +};
Use [Zod](https://zod.dev/), it's already installed and [used to typeguard a Guess.](https://github.com/infinity-keys/ik-landing/blob/main/lib/types.ts#L5-L15) like you're doing here manually for `ThumbnailPack`.

2022-08-23 04:37 UTC, illepic commented on components/puzzles/layout.tsx
> +  puzzles: PublicPuzzlesQuery["puzzles"] | GetAllPacksQuery["packs"];
NICE

2022-08-23 04:37 UTC, illepic commented on lib/types.ts
> +export type ThumbnailPack = GetAllPacksQuery["packs"][0];
NICE

2022-08-23 20:36 UTC, illepic approved these changes

2022-08-23 20:36 UTC, merged