ham/eng 316 rainbow wagmi code cleanup
infinity-keys/ik-landing pull request #304
Opened 2022-08-30 10:21 UTC by ham-evans

- Deleting old wallet stuff
- code cleanup

2022-09-24 04:06 UTC, illepic commented
@ham-evans hit the conflicts and I'll review!

2022-09-29 20:05 UTC, chair28980 requested changes
Remove .env file

2022-09-29 20:05 UTC, chair28980 commented on .env
> +DATABASE_URL="postgresql://hamevans@localhost:5432/ikdb_dev?connection_limit=1"
@ham-evans I don't think we're committing the `.env` file to github

2022-09-29 20:08 UTC, chair28980 submitted a review, later dismissed
i think these files shouldnt be merge either

.yarn/install-state.gz
.redwood/telemetry.txt

2022-09-30 23:42 UTC, chair28980 approved these changes

2022-09-30 23:46 UTC, merged