ENG-301: cookie-consent-banner
infinity-keys/ik-landing pull request #316
Opened 2022-09-02 16:14 UTC by stormcloud266

2022-09-07 15:43 UTC, illepic requested changes

2022-09-07 15:43 UTC, illepic commented on components/cookie-consent.tsx
> +          padding: "8px 20px",
Can we pass classes instead and utilize the roughly equivalent tailwind classes we already have?

2022-09-07 15:43 UTC, illepic commented on components/cookie-consent.tsx
> +        <Link href="/privacy-policy">
So we have this page in our routes?

2022-09-07 15:43 UTC, illepic commented on components/cookie-consent.tsx
> +          </Script>
This moves the gtag stuff to below all content on the page (see `_app.tsx`). Google analytics requires it existing in `<head>` or at least at start of `<body>` so it can jump in before any page interaction. Can we get this logic into `<head>`?

2022-09-07 15:45 UTC, stormcloud266 commented on components/cookie-consent.tsx
> +        <Link href="/privacy-policy">
Yes it is there

2022-09-07 15:48 UTC, stormcloud266 commented on components/cookie-consent.tsx
> +          padding: "8px 20px",
I can pass some, but about half the default styles are inline, so the classes don't override them. I just stuck to all inline for consistency's sake. I can use classes for the ones that work though if that's better.

2022-09-11 04:37 UTC, illepic requested changes

2022-09-11 04:37 UTC, illepic commented on components/cookie-consent.tsx
> +const CookieConsentBanner: FC = () => {
Don't need `FC` anymore.

2022-09-11 04:37 UTC, illepic commented on components/cookie-consent.tsx
> +      }}
Are able to use Tailwind classes here at all? If not, import the resolved tailwind values via javascript: https://tailwindcss.com/docs/configuration#referencing-in-java-script

2022-09-11 04:37 UTC, illepic commented on pages/_document.tsx
> +            src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_INFINITY_KEYS_PUBLIC_GOOGLE_ANALYTICS}`}
Can you build out this url via `new URL()` and then `.toString()` it here

2022-09-11 04:37 UTC, illepic commented on tsconfig.json
> +    "types": ["cypress", "@types/gtag.js"],
Nice.

2022-09-14 22:05 UTC, chair28980 approved these changes
LGTM 🍏

2022-09-20 16:17 UTC, illepic approved these changes

2022-09-20 16:18 UTC, illepic commented
After merge: 

1. Update Vercel secret
2. Update GH Action secret
3. Update `.github/workflows/main.yml` reference.

2022-09-20 17:18 UTC, merged