Itsmekori/eng 322 broken connect wallet text size
infinity-keys/ik-landing pull request #317
Opened 2022-09-06 20:33 UTC by IvySwing

2022-09-07 15:48 UTC, illepic requested changes

2022-09-07 15:48 UTC, illepic commented on next.config.js
> +      "imgs.search.brave.com",
What's going on here?

2022-09-07 15:48 UTC, illepic commented on components/wallet-button.tsx
> +                  <button
Can we instead use our existing `Button` component that we put a lot of work into already, that is already styled and takes in a prop function?

2022-09-07 15:48 UTC, illepic commented on next.config.js
> +      "imgs.search.brave.com",
Ah, these are the chain icons? Toss a comment in here that says that.

2022-09-07 15:48 UTC, illepic commented
Oops, didn't see this was draft and added a review. Apologies.

2022-09-07 20:25 UTC, IvySwing commented on components/wallet-button.tsx
> +                  <button
I left you a message explaining why I went in this particular direction.  The restraint in Rainbow was a big factor.

2022-09-08 19:08 UTC, IvySwing commented
@illepic Also, I need to update the address and name button after wallet connection with a new icon. I will ping you when it's complete

2022-09-11 04:39 UTC, illepic requested changes
Putting this in "request changes" state since we have a few things left to do that we talked about on friday.

2022-09-20 16:20 UTC, illepic approved these changes

2022-09-20 17:54 UTC, merged