ENG-300: api endpoint for delete my email
infinity-keys/ik-landing pull request #318
Opened 2022-09-06 21:08 UTC by stormcloud266

adds api route for deleting users
adds delete user to cypress tests

2022-09-11 04:48 UTC, illepic requested changes
Only some small questions

2022-09-11 04:48 UTC, illepic commented on lib/utils.ts
> +  email && url.searchParams.set("email", email);
Wanted to double check that we want this to make URLs like `/users?userId=23242&jwt=23423423lkj`.

2022-09-11 04:48 UTC, illepic commented on lib/utils.ts
> +  email && url.searchParams.set("email", email);
Note that I think this removes the `/api` off the route.

2022-09-11 04:48 UTC, illepic commented on pages/api/users/index.ts
> +    // });
Noting this is all still commented out.

2022-09-12 14:26 UTC, stormcloud266 commented on lib/utils.ts
> +  email && url.searchParams.set("email", email);
Yes that is the correct url shape, and you're right it did remove api from the route. That's been updated

2022-09-12 14:27 UTC, stormcloud266 commented on pages/api/users/index.ts
> +    // });
Yes just wanted to get the double check on my graphql mutations in the gql file, since I'm deleting users.

2022-09-12 18:25 UTC, stormcloud266 commented on lib/utils.ts
> +  email && url.searchParams.set("email", email);
I actually have a question about this function's use before it gets merged

2022-09-23 23:08 UTC, illepic approved these changes

2022-09-23 23:08 UTC, illepic commented on pages/user/delete.tsx
> +interface Data {
Change to something like `ServerSideProps`

2022-09-23 23:25 UTC, merged