itsmekori/eng-345-fix-failing-cypress-test
infinity-keys/ik-landing pull request #328
Opened 2022-09-09 19:01 UTC by IvySwing

2022-09-09 21:14 UTC, illepic requested changes

2022-09-09 21:14 UTC, illepic commented on cypress/e2e/landing-page.cy.ts
> +  });
Use the input technique seen above to fill in this field.

2022-09-12 16:46 UTC, IvySwing commented on cypress/e2e/landing-page.cy.ts
> +  });
it is done

2022-09-23 20:57 UTC, illepic requested changes

2022-09-23 20:57 UTC, illepic commented on cypress/e2e/landing-page.cy.ts
> +    cy.get('[data-cy="submit"]').contains("Submit").click().wait(1000);
Remove timeout

2022-09-23 20:57 UTC, illepic commented on cypress/e2e/landing-page.cy.ts
> +    cy.contains("Thats not it. Need help?");
Instead of checking entire page, check within the puzzle div for this text.

2022-09-23 20:57 UTC, illepic commented on cypress/e2e/puzzle-dashboard.cy.ts
> +    cy.get('[data-cy="puzzle-link"]').contains("Puzzles").click();
Navigate to page directly instead.

2022-09-23 20:57 UTC, illepic commented on cypress/e2e/puzzle-dashboard.cy.ts
> +    cy.get("a.previous").contains("Previous").click();
Would love it if you validate that content within the page has changed here.

2022-09-24 04:06 UTC, illepic commented
Also hit this conflict!

2022-09-27 21:14 UTC, illepic approved these changes

2022-09-27 21:14 UTC, merged