Update marketing site
infinity-keys/ik-landing pull request #34
Opened 2022-05-20 21:04 UTC by IvySwing

2022-05-26 21:36 UTC, chair28980 commented
![Group 1](https://user-images.githubusercontent.com/29414216/170583653-ccc280b5-eac9-4d31-8e74-29b91459bdfd.png)

1. On hover change color to the same green color in the logo and the border of the Play button.

2. On hover change color to "Twitter blue" (#1DA1F2) and "Discord purple" (#5865F2).

3. On hover change colors on button to black text with green background.

2022-05-27 03:44 UTC, illepic requested changes

2022-05-27 03:44 UTC, illepic commented on components/puzzle.tsx
> +      (fail_route && routeFailUrl(fail_route))
We can handle fail routes at a global config.

2022-05-27 03:44 UTC, illepic commented on tailwind.config.js
> +        twitterBlue: "#1DA1F2",
Nice.

2022-05-27 03:44 UTC, illepic commented
Let's the header bar transition from clear to solid on scroll in this one as well.

2022-05-27 20:18 UTC, chair28980 commented
Tailwind card component: https://tailwind-elements.com/docs/standard/components/cards/

Tailwind accordion component: https://tailwind-elements.com/docs/standard/components/accordion/

Map icons: 

https://icons8.com/icons/set/svg

https://www.flaticon.com/free-icons/svg

2022-05-31 15:56 UTC, chair28980 commented
@IvySwing a few details on the mobile views need tweaking

- Navbar should display all links or group links in a menu
- passcode box breaks on iphone/mobile, should resize to fit to screen

![Group 1 (1)](https://user-images.githubusercontent.com/29414216/171216609-c77048f3-36e9-4b38-bcc6-e43385dcef94.png)

- Padding between sections needed

![Group 2](https://user-images.githubusercontent.com/29414216/171216625-48631b5b-16c9-415d-81f4-9bf046ba8ae8.png)

- adjust lock icon to fit for the section

![Group 3](https://user-images.githubusercontent.com/29414216/171216661-f167777e-6cbd-4fa9-8578-76f68c9b354c.png)

- padding between buttons and new section
- footer links

![Group 4](https://user-images.githubusercontent.com/29414216/171216679-fbdb89d5-0a90-4061-ab5b-a4773d722a1d.png)

2022-05-31 23:15 UTC, chair28980 commented
Tailwind Cards component

https://tailwind-elements.com/docs/standard/components/cards/

2022-06-06 14:30 UTC, chair28980 commented
@IvySwing 

- text not displaying correctly for passcode inputs on mobile view

![Screen Shot 2022-06-06 at 10 29 37 AM](https://user-images.githubusercontent.com/29414216/172181641-df3867b7-b01c-4a92-8e7a-fb34440ebbb7.png)

2022-06-06 16:48 UTC, chair28980 commented
- move hamburger button to the right

![Screen Shot 2022-06-06 at 12 40 40 PM](https://user-images.githubusercontent.com/29414216/172205866-76c6eb0b-1cf2-4684-8c9c-a0e694c462e4.png)

- comment out IK Puzzles Section

2022-06-06 16:53 UTC, chair28980 commented
- Link to new tab on twitter icon

![Screen Shot 2022-06-06 at 12 53 27 PM](https://user-images.githubusercontent.com/29414216/172207970-9fb2135e-4780-464a-887b-9518583ed532.png)

2022-06-06 17:01 UTC, chair28980 commented
Currently the puzzle does not redirect or display any result after a correct or incorrect submission.

- On incorrect submission display `try again` copy.
- On correct submission redirect to treasure page to the `unlock` puzzle

![Screen Shot 2022-06-06 at 12 59 43 PM](https://user-images.githubusercontent.com/29414216/172209004-23baec58-d655-47f9-b346-8dcee0d80be5.png)

2022-06-06 18:32 UTC, IvySwing commented on components/puzzle.tsx
> +      (fail_route && routeFailUrl(fail_route))
The changes were made.

2022-06-06 19:18 UTC, chair28980 requested changes

2022-06-06 19:18 UTC, chair28980 commented on components/header-nav.tsx
> +  { name: "Home", href: "https://www.infinitykeys.io/future/landing" },
```suggestion
  { name: "Home", href: "/" },
```

Please update the the home link to lead to https://infinitykeys.io

We can achieve this by hitting the default route "/".

We cannot hardcode `/future/landing` route as this will not be correct once the marketing page will be live at infinitykeys.io/

2022-06-07 17:16 UTC, illepic requested changes
Just a couple of things.

2022-06-07 17:16 UTC, illepic commented on components/puzzle.tsx
> +            <div className="flex pt-5 pb-5">
Change `pt-5 pb-5` (padding top and padding bottom) to just `py-5` (padding y axis).

2022-06-07 17:16 UTC, illepic commented on pages/index.tsx
> +                    <form action="#" className="sm:max-w-xl sm:mx-auto lg:mx-0">
I know this will be come the Formspree form shortly.

2022-06-07 17:16 UTC, illepic commented on styles/globals.css
> +}
I want to style these both with tailwind classes instead of CSS here.

2022-06-07 17:16 UTC, illepic commented on tailwind.config.js
> +      },
Remove this screen def, we don't need it.

2022-06-07 17:16 UTC, illepic commented on styles/globals.css
> +    }
We don't need to do this. Let's just have boxes that work from 0 until `sm`, no need for another breakpoint.

2022-06-07 19:00 UTC, IvySwing commented on components/puzzle.tsx
> +            <div className="flex pt-5 pb-5">
changes made

2022-06-07 19:04 UTC, IvySwing commented on tailwind.config.js
> +      },
changes made

2022-06-07 19:05 UTC, IvySwing commented on styles/globals.css
> +    }
changes made

2022-06-07 19:19 UTC, IvySwing commented on styles/globals.css
> +}
We tried to apply tailwind classes in the div and directly to the svg, however it only works when it's applied globally using css.

2022-06-08 18:13 UTC, chair28980 approved these changes
LGTM! 🍏

2022-06-09 20:13 UTC, chair28980 commented
Magic's feedback notes:

-Logo on the top nav bar can be removed 

-Text on nav bar needs to be centered on page 

-Change Partner copy to Collab 

-Change Docs copy to Thesis with much smaller copy underneath that says COMING SOON 

-Change Play button copy to Puzzles 

-Change 'Enter Key' copy to 'Solve Puzzle' 

-'You find the clues and you enter the key.'' copy is out of order. 

-Can we make the IK logo in the center 2X bigger? 

-Can we see what left justified copy looks like for all of the copy on that section? 

-Change 'Hunt for clues anywhere, like embedded in this page' to Hunt for clues anywhere' 

-Add an underline to the last e in anywhere. 

-Bold all of the underlined letters 

-Can the top nav bar follow us down the page? 

-Brighten the font on the 'What is Infinity Keys?' section 

-Remove the copy 'Find out how it works below' 

-Remove the copy 'Infinity Keys is a platform to build puzzles, hunts, and treasure.' 

-Remove the copy 'If you are a brand interested in integrating an Infinity Keys puzzle please contact us here' 

-Change 'Sign Up for Our Newsletter!' copy to 'Sign up for email updates.' 

-Adjust bottom nav bar to match top nav bar

2022-06-09 20:54 UTC, closed without merging