Itsmekori/eng 358 refactoring logic to accept additional iframes
infinity-keys/ik-landing pull request #392
Opened 2022-09-21 19:07 UTC by IvySwing

2022-09-21 19:15 UTC, IvySwing commented
@illepic Quick note: we had to use inline styling for the aspect ratio in the iframe.tsx component because it will not accept tailwind classes.

2022-09-21 19:26 UTC, illepic requested changes

2022-09-21 19:26 UTC, illepic commented on components/iframe.tsx
> +  aspect: string;
Why are we doing this? What content would need an aspect ratio other than square, 16x9, or some other finite enum?

2022-09-22 15:47 UTC, IvySwing commented on components/iframe.tsx
> +  aspect: string;
@illepic There have been two cases where the embed that was provided by partners that we needed to use a custom aspect ratio. Based on that, and other factors, we decided it would be best to set up logic to customize the aspect ratio.  Besides being able to adjust for various embeds we will have in the future, it also eliminates a full step in the puzzle testing and puzzle creation process.

2022-09-23 21:19 UTC, illepic requested changes

2022-09-23 21:19 UTC, illepic commented on components/iframe.tsx
> +  aspect: string;
Please leave a comment that anything with an aspect ratio will be parsed as an iframe.

2022-09-23 21:19 UTC, illepic commented on components/iframe.tsx
> +    // { "aspect-[4/3] sm:aspect-[1.4]": aspect === "crossword" }
nuke this

2022-09-23 21:19 UTC, illepic commented on components/markdown.tsx
> +        const isEmbed =
const [words] = children;

// Now use `words` instead of `children[0]`

2022-09-23 21:19 UTC, illepic commented on components/markdown.tsx
> +        if (isEmbed) {
use an early return so we don't nest

```
if (!embed) return;
```

2022-09-23 21:19 UTC, illepic commented on components/markdown.tsx
> +            typeof children[0] === "string" ? children[0]?.split("|") : [];
Become:

```
const options = words.split('|');
```

2022-09-23 21:19 UTC, illepic commented on components/markdown.tsx
> +          const aspectRatio = options[1].trim();
if (!options[1]) throw new Error('Aspect ratio required because of | found in embed string.');

2022-09-27 21:14 UTC, illepic approved these changes

2022-09-27 21:14 UTC, merged