ENG-396: custom images in social previews
infinity-keys/ik-landing pull request #395
Opened 2022-09-22 18:18 UTC by stormcloud266

- create seo component, remove meta from _document, update index page
- update all pages to use seo component. use dynamic data in pack/puzzles

2022-09-22 21:04 UTC, chair28980 approved these changes
Awesomeeee LGTM 🍏

2022-09-24 04:36 UTC, illepic requested changes
Only a tiny thing.

2022-09-24 04:36 UTC, illepic commented on components/seo.tsx
> +  imageUrl,
```ts
imageUrl = new URL("treasure.jpeg", IK_CLAIMS_NAMESPACE)
```
Then down below everywhere you refer to `formattedImageUrl`, use `imageUrl`

2022-09-24 17:00 UTC, illepic approved these changes

2022-09-24 18:20 UTC, merged