ENG-401: show solved puzzles in pack
infinity-keys/ik-landing pull request #401
Opened 2022-09-23 20:53 UTC by stormcloud266

2022-09-23 21:13 UTC, chair28980 approved these changes
LGTM 🍏 !

2022-09-24 04:46 UTC, illepic requested changes
Get with me for some quick questions. Also merge conflict.

2022-09-24 04:46 UTC, illepic commented on pages/api/minter/check-balance.ts
> +  const claimed = claimedTokens?.every((b) => b);
Are you just looking to copy `claimedTokens` to `claimed`? If so, just

```ts
const claimed = [...claimedTokens];
```

2022-09-24 04:46 UTC, illepic commented on pages/api/minter/verify.ts
> +    tokensClaimed = claimedTokens;
Get with me to help me understand why we're copying one object to another. Since javascript passes by reference for objects, changing anything in one will change in the other with this kind of assignment.

2022-09-25 20:00 UTC, illepic approved these changes

2022-09-25 20:16 UTC, merged