Itsmekori/eng 340 create node scripts to update puzzles in database (DO NOT MERGE)
infinity-keys/ik-landing pull request #402
Opened 2022-09-23 21:24 UTC by IvySwing

2022-09-23 22:41 UTC, illepic requested changes

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +const gql = `query MyQuery($siteName: String) {
Give it a name.

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +const gqlModify = `mutation MyMutation($simple_name: String, $input_type: puzzle_input_type_enum = boxes, $challenge: String = "", $fail_message: String = "", $landing_message: String = "", $solution
Mutation with object instead is an option.

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +const gqlAllPuzzles = `query MyPuzzles {
Give name.

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +const gqlModify = `mutation MyMutation($simple_name: String, $input_type: puzzle_input_type_enum = boxes, $challenge: String = "", $fail_message: String = "", $landing_message: String = "", $solution
Give name.

2022-09-23 22:41 UTC, illepic commented on tsconfig.json
> +  }
Nuke this since not needed.

2022-09-23 22:41 UTC, illepic commented on package.json
> +    "tsconfig-paths": "^4.1.0",
Nuke this since not needed.

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +const gql = `query MyQuery($siteName: String) {
Nuke this one, dupe'd below.

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +  console.log(results);
Nuke.

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +  );
Nuke.

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +  const getResults = await getPuzzles.json();
Variables that start with a verb are always a function! Please change var name to not start with verb, ie call this `ogPuzzles`.

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +          (puzzle) => puzzle.simple_name === String(change.simple_name)
Remove `String()` wherever possible

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +          solution: getGoodData(change["Input (Passcode)"], oldPuzzle.solution),
```
solution: !change["Instructions (old landing_message)"] ? oldPuzzle.solution : change["Instructions (old landing_message)"]
```

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +  };
```
const getGoodData = (newData, oldData) => newData || oldData;
```

2022-09-23 22:41 UTC, illepic commented on scripts/import.mjs
> +  const updatePuzzles = async (variables) => {
Change `variables` to something relevant.

2022-09-26 20:54 UTC, stormcloud266 requested changes

2022-09-26 20:54 UTC, stormcloud266 commented on scripts/import.mjs
> +    //     newPuzzInfo,
this will need to be `variables: newPuzzInfo`

2022-09-26 20:54 UTC, stormcloud266 commented on yarn.lock
> +
If `tsconfig-paths` was removed from the package.json, let's also run `yarn remove tsconfig-paths` so it deletes it from here as well.

2022-09-26 21:15 UTC, stormcloud266 approved these changes
Great job this rocks

2022-09-26 23:27 UTC, illepic approved these changes

2022-09-28 01:13 UTC, closed without merging