Eng-402: add go to pack button
infinity-keys/ik-landing pull request #403
Opened 2022-09-23 22:00 UTC by stormcloud266

2022-09-24 04:50 UTC, illepic requested changes
Tiny things.

2022-09-24 04:50 UTC, illepic commented on components/minter.tsx
> +        " text-blue font-bold rounded-md py-2 px-4 min-w-[11rem] text-lg border border-solid",
Can we set a min width that's one of the preexisting instead of making a new one. There has to be a tailwind class that's already close to 11rem.

2022-09-24 04:50 UTC, illepic commented on components/minter.tsx
> +            text={buttonText ? buttonText : `Go to ${parentPackName}`}
```ts
text={buttonText || `Go to ${parentPackName}`}
```

2022-09-24 14:45 UTC, stormcloud266 commented on components/minter.tsx
> +        " text-blue font-bold rounded-md py-2 px-4 min-w-[11rem] text-lg border border-solid",
There are only a few built-in min-width classes and they are 0px, 100%, or content based.  w-44 is 11rem which is where I got that value

2022-09-25 19:57 UTC, illepic approved these changes

2022-09-25 19:57 UTC, merged