ENG-475: trigger reply email
infinity-keys/ik-landing pull request #482
Opened 2022-10-14 14:35 UTC by stormcloud266

- update user model required/optional fields
- regenerate user sdl
- get email submission logic working
- clean up. add email validation
- add relationships in db
- rename id fields. generate sdls for models

2022-10-19 18:19 UTC, illepic requested changes

2022-10-19 18:19 UTC, illepic commented on api/db/schema.prisma
> +  puzzleId String @unique
Multiple `Step`s will have the same `puzzleId`, so this `@unique` annotation will explode.

2022-10-19 18:19 UTC, illepic commented on api/db/schema.prisma
> +  address String?
Let's change this to be be JSON where the shape can be either `{ email: string; }` or `{address: string; }`

2022-10-20 15:29 UTC, stormcloud266 commented on api/db/schema.prisma
> +  puzzleId String @unique
When I remove this `@unique` I get 

`Error parsing attribute "@relation": A one-to-one relation must use unique fields on the defining side. Either add an `@unique` attribute to the field `puzzleId`, or change the relation to one-to-many.`

should I change the puzzle's nft to an array or go about this a different way?
```graphql
model Puzzle {
  ...
  nft Nft[]
}
```

2022-10-20 15:52 UTC, illepic commented on api/db/schema.prisma
> +  puzzle Puzzle @relation(fields: [puzzleId], references: [puzzleId])
```
puzzle Puzzle?
```

2022-10-20 17:44 UTC, illepic approved these changes

2022-10-20 17:44 UTC, merged