ENG-517: migrate nft check api routes
infinity-keys/ik-landing pull request #533
Opened 2022-11-01 15:09 UTC by stormcloud266

- add abis, service, sdl

2022-11-09 05:33 UTC, illepic requested changes

2022-11-09 05:33 UTC, illepic commented on api/src/services/minter/check-nft.ts
> +import { RPCLookup } from 'src/lib/walletConstants'
We have the new, shared `@infinity-keys/contracts` package. Can we move this stuff over there?

2022-11-09 05:33 UTC, illepic commented on api/src/services/minter/check-nft.ts
> +      return { success: false }
Since we are catching the error and then just returning `{success: false}`, there's no need for a `try/catch` in any of these.

2022-11-09 05:33 UTC, illepic commented on api/src/services/minter/check-nft.ts
> +  return { success: true, nftPass }
The graphql type above indicates this should have a `message` key as well, I believe.

2022-11-09 15:28 UTC, stormcloud266 commented on api/src/services/minter/check-nft.ts
> +  return { success: true, nftPass }
The messages are optional in these minter services

2022-11-18 16:42 UTC, illepic approved these changes

2022-11-18 16:43 UTC, merged