Itsmekori/eng 507 build tetris integration
infinity-keys/ik-landing pull request #606
Opened 2022-12-14 20:35 UTC by IvySwing

migrated files from local to redwood branch and test to see if it works as a component.

2022-12-15 17:28 UTC, stormcloud266 requested changes
This is really rad, just a couple small things

2022-12-15 17:28 UTC, stormcloud266 commented on web/src/components/TetrisGameApp/index.js
> +)
We won't need this file now that it's a component and not a stand alone app

2022-12-15 17:28 UTC, stormcloud266 commented on web/src/components/TetrisGameApp/components/GameController.css
> +.GameController {
Just a note for later, this is why it keeps jumping to the top of the page. It's autofocusing on the input which is positioned -100em above the game.

2022-12-15 17:28 UTC, stormcloud266 commented on web/src/components/TetrisGameApp/components/Menu.css
> +  border-style: solid;
Let's do a little padding here just so the text isn't right up against the border

<img width="383" alt="Screenshot 2022-12-15 at 10 23 25 AM" src="https://user-images.githubusercontent.com/19338130/207927408-b061f629-d391-4d28-b11a-d3edeb9e2b49.png">

2022-12-16 18:24 UTC, IvySwing commented on web/src/components/TetrisGameApp/index.js
> +)
@stormcloud266 file has been deleted

2022-12-16 18:27 UTC, IvySwing commented on web/src/components/TetrisGameApp/components/GameController.css
> +.GameController {
@stormcloud266 I made a comment in the GameController.css file to reference the issue with the jump to the top of page

2022-12-16 18:35 UTC, IvySwing commented on web/src/components/TetrisGameApp/components/Menu.css
> +  border-style: solid;
![image](https://user-images.githubusercontent.com/43865262/208165959-a38d22ba-fe67-423f-a82a-3a07826ac0d2.png)

@stormcloud266 let me know your thoughts

2022-12-16 18:44 UTC, stormcloud266 approved these changes
Awesome

2022-12-16 18:45 UTC, stormcloud266 commented on web/src/components/TetrisGameApp/components/Menu.css
> +  border-style: solid;
looks good!

2022-12-16 18:49 UTC, merged