ENG-603: Claim page and minting
infinity-keys/ik-landing pull request #619
Opened 2022-12-29 17:33 UTC by stormcloud266

Please don't merge until both [eng-459](https://github.com/infinity-keys/ik-landing/pull/598) and [eng-591](https://github.com/infinity-keys/ik-landing/pull/600) are in redwood

2023-02-02 21:48 UTC, stormcloud266 commented on api/src/services/ik/minter/claim.ts
> +
@illepic Should we do some sort of cookie check here? Not sure how to handle a pack if we do...

2023-02-02 21:51 UTC, stormcloud266 commented on api/src/services/ik/attempts/attempts.ts
> +
@illepic I'm rejecting attempts here if the rewardable has already been "solved". Should we do this using the cookie in the function? Or both maybe

2023-02-03 17:06 UTC, illepic requested changes

2023-02-03 17:06 UTC, illepic commented on api/src/services/ik/attempts/attempts.ts
> +    }
Leave here, but let's check cookie for prior solves on this step instead of always hitting db.

2023-02-03 17:06 UTC, illepic commented on api/src/services/ik/attempts/attempts.ts
> +                rewardableId: step.puzzle.rewardable.asChild[0].parentId,
Make packId clearer here

2023-02-03 17:06 UTC, illepic commented on api/src/services/ik/minter/claim.ts
> +  if (!rewardableData || rewardableData.userRewards.length < 1) {
```
=== 0
```

2023-02-03 17:06 UTC, illepic commented on api/src/services/ik/minter/claim.ts
> +      success: true,
Try `false`, what happens

2023-02-03 17:06 UTC, illepic commented on api/src/services/ik/minter/claim.ts
> +  const isPack = rewardableData.asParent.length > 0
Also check for type, using type enum.

2023-02-08 16:46 UTC, illepic approved these changes

2023-02-08 16:46 UTC, illepic commented on api/src/services/ik/attempts/attempts.ts
> +          })
Just double check parent type is what we're looking for, ie `pack`.

2023-02-08 16:46 UTC, illepic commented on api/src/services/ik/minter/claim.ts
> +          'You do not have the required NFTs on this chain. Please ensure you have completed the above puzzles and are on the correct chain.',
List NFT ids/names here, since we know them.

2023-02-08 16:46 UTC, illepic commented on api/src/services/ik/rewardables/rewardables.ts
> +        where: { userId: context.currentUser.id },
Import `context`.

2023-02-08 16:46 UTC, illepic commented on web/src/pages/ClaimPage/ClaimPage.tsx
> +
```ts
const canClaim = !signature && !claimed && isConnected && isValidChain;
```

2023-02-08 16:46 UTC, illepic commented on web/src/pages/ClaimPage/ClaimPage.tsx
> +  const isValidChain = validChain(chain?.id || 0)
Update `validChain` to take in `number | undefined`

2023-02-08 16:47 UTC, merged