ENG-626: save user attempts to db
infinity-keys/ik-landing pull request #631
Opened 2023-01-03 22:13 UTC by stormcloud266

- save attempts to DB
- enable first time sign in, add makeattempt

2023-01-24 17:00 UTC, illepic requested changes

2023-01-24 17:00 UTC, illepic commented on api/src/functions/attempt/attempt.ts
> +}
Move to function.

2023-01-24 17:00 UTC, illepic commented on api/src/functions/attempt/attempt.ts
> +const getSteps = (completed: PuzzlesDataType, puzzle: string, step: string) => {
Change name to `addStepToCompletedSteps`

2023-01-24 17:00 UTC, illepic commented on api/src/functions/attempt/attempt.ts
> +}
Consolidate.

2023-01-24 17:00 UTC, illepic commented on api/src/functions/attempt/attempt.ts
> +    // trying to check a step they aren't allowed to see
Throw comments in here and make `stepNum`.

2023-01-24 17:00 UTC, illepic commented on api/src/services/ik/attempts/attempts.ts
> +const decryptCookie = (data: string | undefined) => {
Move these to the encode src

2023-01-24 17:00 UTC, illepic commented on api/src/services/ik/attempts/attempts.ts
> +  return step({ id })
Comments plx

2023-01-24 17:00 UTC, illepic commented on web/src/components/RewardablePack/RewardablePack/RewardablePack.tsx
> +    <Wrapper full fullHeight>
Can this be a Set?

2023-01-24 17:00 UTC, illepic commented on web/src/components/RewardablePack/RewardablePackCell/RewardablePackCell.tsx
> +  <Wrapper fullHeight>
Let's see if we need to Set this too

2023-01-24 17:00 UTC, illepic commented on web/src/components/RewardablePuzzle/RewardablePuzzle/RewardablePuzzle.tsx
> +const cloudinaryId = 'ik-alpha-trophies/Map-04_xzczep'
Noting here we'll use real NFT info from migration

2023-01-24 17:00 UTC, illepic commented on web/src/components/RewardablePuzzle/RewardablePuzzle/RewardablePuzzle.tsx
> +const cloudinaryId = 'ik-alpha-trophies/Map-04_xzczep'
Need to link NFT to puzzle in the migration

2023-01-24 17:00 UTC, illepic commented on web/src/components/RewardablePuzzle/RewardablePuzzle/RewardablePuzzle.tsx
> +  const stepIndex = stepParam && parseInt(stepParam, 10) - 1
Make `stepNum` because we parse `stepParam` twice.

2023-01-24 17:00 UTC, illepic commented on web/src/components/Wrapper/Wrapper.tsx
> +        fullHeight ? 'min-h-screen' : ' min-h-[calc(100vh-80px)]',
We can do this without calc()

2023-01-24 17:57 UTC, stormcloud266 commented on web/src/components/RewardablePack/RewardablePack/RewardablePack.tsx
> +    <Wrapper full fullHeight>
Made a separate ticket for these since we'll have to touch a few unrelated pages

2023-01-24 17:57 UTC, stormcloud266 commented on web/src/components/RewardablePuzzle/RewardablePuzzle/RewardablePuzzle.tsx
> +const cloudinaryId = 'ik-alpha-trophies/Map-04_xzczep'
Made another ticket for this as well

2023-01-25 16:32 UTC, illepic approved these changes

2023-01-25 16:32 UTC, merged