eng-665: add nft check step type
infinity-keys/ik-landing pull request #665
Opened 2023-01-30 20:42 UTC by stormcloud266

- add nft check to schema, attempt, and makeattempt. add nft check button

2023-02-09 16:28 UTC, illepic commented on api/src/functions/attempt/attempt.ts
> +      stepType: stepType as StepType,
Should be type, will screenshare.

2023-02-09 17:06 UTC, illepic requested changes

2023-02-09 17:06 UTC, illepic commented on api/src/services/ik/attempts/attempts.ts
> +      [type]: true,
Instead of per-type dynamic fetching, let's get ALL fields, only one will have data.

2023-02-09 17:06 UTC, illepic commented on api/src/graphql/steps.sdl.ts
>      SIMPLE_TEXT
Add comment showing name of Model for each of these.

2023-02-09 17:06 UTC, illepic commented on api/src/services/ik/minter/check-nft.ts
> +    )
```ts
const args = [account, number ?? null].filter(Null);
const balance = await contract.balanceOf(...args);
```

2023-02-09 17:06 UTC, illepic commented on packages/constants/src/index.ts
> +
Let's use the graphql types instead.

2023-02-09 17:06 UTC, illepic commented on packages/constants/src/index.ts
> +  [key: string]: string
Make sure the key uses the step type enum from graphql codegenerated ts types.

2023-02-09 17:06 UTC, illepic commented on web/src/hooks/useMakeAttempt.tsx
> +}
Make `type` instead of `interface`

2023-02-09 17:06 UTC, illepic commented on web/src/hooks/useMakeAttempt.tsx
> +    apiUrl.searchParams.set('stepType', stepType)
This guy goes bye bye.

2023-02-09 17:06 UTC, illepic commented on web/src/hooks/useMakeAttempt.tsx
> +      console.log(e)
console.error()

2023-02-09 17:06 UTC, illepic commented on web/src/components/NftCheckButton/NftCheckButton.tsx
> +    if (!address) return
throw so they knew there's no wallet address.

2023-02-09 17:06 UTC, illepic commented on web/src/components/NftCheckButton/NftCheckButton.tsx
> +      account: address,
`address`

2023-02-09 17:06 UTC, illepic commented on web/src/components/NftCheckButton/NftCheckButton.tsx
> +        <>
div this

2023-02-09 21:30 UTC, stormcloud266 commented on web/src/components/NftCheckButton/NftCheckButton.tsx
> +      account: address,
this is `account` every where except when pulling it from the wagmi hook. i can update it if address is better, but i'll do that in a separate PR

2023-02-09 21:32 UTC, stormcloud266 commented on web/src/components/NftCheckButton/NftCheckButton.tsx
> +    if (!address) return
I'm removing the button entirely if they aren't connected

2023-02-15 17:26 UTC, illepic approved these changes

2023-02-15 17:26 UTC, merged