ENG-713: check multiple NFTs per step
infinity-keys/ik-landing pull request #686
Opened 2023-02-14 21:49 UTC by stormcloud266

Allows us to check for multiple NFTs and POAPs per step. Can require all NFTs or only one.

2023-02-15 15:40 UTC, chair28980 approved these changes
multi check yourself before you wreck yourself 🍏

2023-02-24 17:24 UTC, illepic requested changes

2023-02-24 17:24 UTC, illepic commented on api/db/schema.prisma
> +model StepNftCheck {
Comments explain on all this.

2023-02-24 17:24 UTC, illepic commented on api/src/services/ik/minter/check-nft.ts
> +  const url = `https://api.poap.tech/actions/scan/${account}/${poapEventId}`
Let's use `new URL()`.

2023-03-01 17:59 UTC, illepic commented on api/src/services/ik/minter/check-nft.ts
> +    const res = await fetch(url.toString(), options)
Does this `fetch` shim require `url` to be string or will it take a real `URL` object?

2023-03-01 18:00 UTC, illepic approved these changes
only one question

2023-03-01 18:03 UTC, stormcloud266 commented on api/src/services/ik/minter/check-nft.ts
> +    const res = await fetch(url.toString(), options)
It only supports string in this version unfortunately. But if we use v2 instead of v3, it looks like it does support URL and we don't have to do that dynamic import

2023-03-01 18:04 UTC, merged