ENG-729: add support for anonymous puzzles and steps
infinity-keys/ik-landing pull request #709
Opened 2023-02-21 18:58 UTC by stormcloud266

- regen sdl for puzzles
- add component tests

2023-02-21 20:58 UTC, stormcloud266 commented on api/src/services/ik/steps/steps.ts
> +}
Turns out I did need both so we could keep our old optionalStep query behind requireAuth

2023-02-21 21:00 UTC, stormcloud266 commented on api/src/graphql/ik/attempts.sdl.ts
> -  }
Just moving our step stuff out of these attempts files

2023-02-21 21:03 UTC, stormcloud266 commented on api/src/services/ik/attempts/attempts.ts
> -  // authenticated users should be allowed to view first steps
This whole function was moved to `steps` but I also deleted this check and made the non-anon query requireAuth

2023-02-21 21:11 UTC, stormcloud266 commented on web/src/components/StepsCell/StepsCell.tsx
> -          />
In the `StepsCell` this `isAuthenticated` check now just routes to `anonPuzzle` if they aren't authenticated

2023-02-21 21:22 UTC, stormcloud266 commented on api/src/graphql/ik/steps.sdl.ts
> +    anonOptionalStep(id: String, puzzleId: String, stepNum: Int): Step @skipAuth
This is the new one

2023-03-01 16:38 UTC, illepic requested changes

2023-03-01 16:38 UTC, illepic commented on api/src/services/ik/steps/steps.ts
> +  context: RedwoodGraphQLContext
Let's use global context instead.

2023-03-01 16:38 UTC, illepic commented on web/src/components/PuzzleLandingLayout/PuzzleLandingLayout.tsx
> +    | NonNullable<FindRewardablePuzzleBySlug['rewardable']>
Double check that `NonNullable` is needed here.

2023-03-01 16:38 UTC, illepic commented on web/src/components/PuzzleLandingLayout/PuzzleLandingLayout.tsx
> +interface PuzzleLandingLayoutProps extends PropsWithChildren {
Let's get this into a Layout/Set

2023-03-01 16:38 UTC, illepic commented on web/src/components/StepsLayout/StepsLayout.tsx
> +            <SimpleTextInput
Try dynamic import here.

2023-03-01 17:31 UTC, stormcloud266 commented on api/src/services/ik/steps/steps.ts
> +  context: RedwoodGraphQLContext
Global context gives me this error about it being type unknown:

![Screenshot 2023-03-01 at 10 26 53 AM](https://user-images.githubusercontent.com/19338130/222216347-8bddfa50-2db0-4a9f-b809-da8fdd6dadee.png)


whereas it comes in typed getting it from the params:

![Screenshot 2023-03-01 at 10 27 43 AM](https://user-images.githubusercontent.com/19338130/222217055-4b9d7c4d-7ac0-4b0d-ad5d-a8eddb49571b.png)

2023-03-01 17:36 UTC, stormcloud266 commented on web/src/components/PuzzleLandingLayout/PuzzleLandingLayout.tsx
> +interface PuzzleLandingLayoutProps extends PropsWithChildren {
So I actually have to pass in the rewardable to this layout on each page, so I don't think I'll be able to move this into a set

2023-03-01 17:51 UTC, illepic approved these changes

2023-03-01 18:07 UTC, merged