ENG-735: update collab section
infinity-keys/ik-landing pull request #716
Opened 2023-02-23 17:33 UTC by Richard-Burd

The 'Collab' section is transformed into a 'Build' section as we no longer want to display our collab partners on the homepage.

2023-02-23 20:14 UTC, stormcloud266 requested changes

2023-02-23 20:14 UTC, stormcloud266 commented on web/src/pages/HomePage/HomePage.tsx
> +        <div className="mx-auto max-w-xl">
Let's make this section have the same max width as the section above

2023-02-23 20:14 UTC, stormcloud266 commented on web/src/pages/HomePage/HomePage.tsx
> +            <ul className="list-disc ml-6 space-y-4 md:space-y-0 text-indigo-200 ">
Can you add the same margin top to this list as well

2023-02-23 20:14 UTC, stormcloud266 commented on web/src/pages/HomePage/HomePage.tsx
> +            </Link>
Checkout how Redwood does [named routes](https://redwoodjs.com/docs/router#link-and-named-route-functions). It makes it so we can change path in `Routes` and not have to change any of our `Link` hrefs.

This looks rad btw

2023-03-01 16:46 UTC, illepic requested changes

2023-03-01 16:46 UTC, illepic commented on web/src/components/Header/Header.tsx
> +                  <a
Let's add `rel=noopener`, `re for each a tag.

2023-03-01 16:46 UTC, illepic commented on web/src/pages/HomePage/HomePage.tsx
> +        console.log("we're at line 42 right here")
Nuke the console.log.

2023-03-01 16:46 UTC, illepic commented on web/src/pages/HomePage/HomePage.tsx
> +import CollapsibleMarkdownStories from 'src/components/CollapsibleMarkdown/CollapsibleMarkdown.stories'
Remove, this was accidental import.

2023-03-01 23:12 UTC, illepic approved these changes

2023-03-01 23:30 UTC, merged