ENG-746: profile card uses real data
infinity-keys/ik-landing pull request #724
Opened 2023-03-02 19:28 UTC by stormcloud266

2023-03-03 16:42 UTC, illepic requested changes
Need the migration sql files

2023-03-06 17:16 UTC, stormcloud266 commented
> Need the migration sql files

@illepic Running migrate dev/reset doesn't give me a migration and it says "already in sync"

2023-03-06 17:21 UTC, illepic commented
> > Need the migration sql files
> 
> @illepic Running migrate dev/reset doesn't give me a migration and it says "already in sync"

Maybe the migration snuck into a pull request prior to this.

2023-03-06 17:21 UTC, illepic approved these changes

2023-03-06 17:21 UTC, merged