ENG-739: embedded homepage puzzle
infinity-keys/ik-landing pull request #731
Opened 2023-03-05 21:44 UTC by Richard-Burd

2023-03-06 16:09 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
>  import RICIBs from 'react-individual-character-input-boxes'
```ts
import React from 'react'
```

2023-03-06 16:09 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> -import {
Leave a top-level comment describing what this file does in this format.

2023-03-06 16:27 UTC, illepic requested changes

2023-03-06 16:27 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +import { FormEvent } from 'react'
Combine these 2.

2023-03-06 16:27 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +const Puzzle = () => {
We're going to have a prop here called `answer`, which we'll use to send in the string for the inputs.

2023-03-06 16:27 UTC, illepic commented on web/src/pages/HomePage/HomePage.tsx
> +            <Puzzle /> {/* hard-coded; doesn't need any props */}
We'll be able to do something like this:

```ts
<Puzzle answer="kittens"/>
```

2023-03-06 16:27 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +    const inputText = Array.from(e.currentTarget.getElementsByTagName('input'))
We'll have a different argument to `Array.from()` instead of `e.currentTarget...`

2023-03-06 16:27 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +  const puzzleAnswer: string = 'unlock'
Don't need `: string`

2023-03-06 16:27 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +      }
We'll rip this out.

2023-03-06 16:27 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +            amount={6}
We'll get this dynamic from the answer

2023-03-06 16:27 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +              className: 'ik-code-input',
this will be from answer.

2023-03-07 16:23 UTC, illepic requested changes

2023-03-07 16:23 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +      setShowFail(true)
Move this inside the timeout

2023-03-07 16:23 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +      setShowPlayMoreButton(true)
We want this to only show after loading spinner.

2023-03-07 16:23 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +      <>
Nuke the fragment if we can.

2023-03-08 16:39 UTC, illepic requested changes

2023-03-08 16:39 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +      setShowPlayMoreButton(true)
Delete this piece of state.

2023-03-08 16:39 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +        </div>
Make sure this disappears when the puzzle is "processing".

2023-03-08 16:39 UTC, illepic commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +  if (showPlayMoreButton) {
`showSuccess`

2023-03-09 06:21 UTC, Richard-Burd commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +  if (showPlayMoreButton) {
This was re-named to something that makes sense

2023-03-09 06:21 UTC, Richard-Burd commented on web/src/components/PuzzleOriginal/Puzzle.tsx
> +      setShowPlayMoreButton(true)
I think we need both states

2023-03-09 16:16 UTC, illepic approved these changes

2023-03-09 16:16 UTC, illepic commented on web/src/components/Button/Button.tsx
> +        'border-turquoise hover:border-turquoise': disabled,
Take these 2 lines and consolidate to 52.

2023-03-09 16:16 UTC, merged