'Heroes of Evermore' wraps nicely
infinity-keys/ik-landing pull request #749
Opened 2023-03-10 21:29 UTC by Richard-Burd

Some of the text is being cut off in the `Bars4Icon` that is in the `<GridLayoutButtons />` component...for example, the last "e" in "Evermore"  this can be solved by using `break-word` instead of `break all`

2023-03-11 00:09 UTC, stormcloud266 requested changes

2023-03-11 00:09 UTC, stormcloud266 commented on web/src/components/Thumbnail/Thumbnail.tsx
> +        'puzzle-thumb break-word relative block w-full max-w-[18rem] cursor-pointer rounded-lg border border-transparent bg-blue-800 shadow transition hover:border-turquoise',
looks like the tailwind class is actually `break-words`

https://tailwindcss.com/docs/word-break#break-words

2023-03-11 02:04 UTC, Richard-Burd commented on web/src/components/Thumbnail/Thumbnail.tsx
> +        'puzzle-thumb break-word relative block w-full max-w-[18rem] cursor-pointer rounded-lg border border-transparent bg-blue-800 shadow transition hover:border-turquoise',
correct...I had a typo.

2023-03-11 02:19 UTC, stormcloud266 approved these changes
awesome!

2023-03-13 15:06 UTC, illepic approved these changes

2023-03-13 15:06 UTC, merged