ENG-805: play page
infinity-keys/ik-landing pull request #779
Opened 2023-03-16 20:22 UTC by stormcloud266

- adds play page
- adds support for combining multiple types of rewardables in grid pages

<img width="1305" alt="Screenshot 2023-03-16 at 2 23 56 PM" src="https://user-images.githubusercontent.com/19338130/225744068-d2d38cf3-83a8-4944-b774-86728b8d0b11.png">

2023-03-16 20:45 UTC, chair28980 commented
supa hot fire

2023-03-17 00:52 UTC, illepic commented on web/src/components/RewardablesCell/RewardablesCell.tsx
> +}) => {
Amazing.

2023-03-17 00:55 UTC, illepic requested changes

2023-03-17 00:55 UTC, illepic commented on web/src/components/RewardablesGrid/RewardablesGrid.tsx
> +}: RewardablesListProps) => {
Just inline the type here. I like that better than a standalone type that's only used once.

2023-03-17 00:58 UTC, illepic approved these changes

2023-03-17 00:59 UTC, merged