convert login message to button
infinity-keys/ik-landing pull request #789
Opened 2023-03-19 16:56 UTC by Richard-Burd

2023-03-20 15:05 UTC, stormcloud266 requested changes

2023-03-20 15:05 UTC, stormcloud266 commented on web/src/components/RewardablePuzzle/RewardablePuzzle/RewardablePuzzle.tsx
> +            <Button text="login to play" to={'/profile'} />
Let's use the `to={routes.profile()}` here. We also might need some text that says something like "Must be logged in to play"

2023-03-21 15:13 UTC, illepic approved these changes

2023-03-21 15:14 UTC, illepic approved these changes

2023-03-21 15:14 UTC, stormcloud266 approved these changes

2023-03-21 15:14 UTC, merged