ENG-827: add functionCall stepType
infinity-keys/ik-landing pull request #799
Opened 2023-03-23 19:38 UTC by stormcloud266

- add new step type schema. generate sdl
- add function check step type

2023-03-27 15:58 UTC, illepic commented on api/db/migrations/migration_lock.toml
Interesting. Where does this come from?

2023-03-27 16:10 UTC, illepic requested changes

2023-03-27 16:10 UTC, illepic commented on api/src/lib/web3/check-function-call.ts
> +  import('node-fetch').then(({ default: fetch }) => fetch(url, init))
We only need dynamic imports for the frontend. Backend is all pre-compiled and can be as chungus as we want.

2023-03-27 16:10 UTC, illepic commented on api/src/lib/web3/check-function-call.ts
> +  url.searchParams.set('methodIds', methodIds.join(','))
I believe you can do something like:

```ts
methodIds.forEach((methodId) => { url.searchParams.set('methodIds', methodId) })
```
The URL parsing on the backend should handle multiple `&methodId=thing&methodId=otherThing`

2023-03-27 16:10 UTC, illepic commented on api/src/lib/web3/check-function-call.ts
> +  // }
Let's talk about how we'll gate this at the gql or redwood function level.

2023-03-27 16:10 UTC, illepic commented on api/src/lib/web3/check-function-call.ts
> +    const res = await fetch(url.toString())
`fetch()` can take in raw URL: `const res = await fetch(url)`

2023-03-27 16:10 UTC, illepic commented on api/src/lib/web3/check-function-call.ts
> +    const data: FunctionCallResData = await res.json()
No need for `:FunctionCallResData` since you're `parse` below will handle it.

2023-03-27 16:10 UTC, illepic commented on api/src/services/stepFunctionCalls/stepFunctionCalls.ts
> +export const StepFunctionCall: StepFunctionCallRelationResolvers = {
Any reason this is not `camelCase`?

2023-03-27 16:10 UTC, illepic commented on web/src/components/StepsLayout/StepsLayout.tsx
> +
Niiiiice.

2023-03-27 16:14 UTC, stormcloud266 commented on api/db/migrations/migration_lock.toml
Not entirely sure, it showed up when I ran `migrate dev`

2023-03-27 16:15 UTC, stormcloud266 commented on api/src/lib/web3/check-function-call.ts
> +  import('node-fetch').then(({ default: fetch }) => fetch(url, init))
The version of fetch we're using is ESM only and doesn't work on the api side without the dynamic import

2023-03-27 16:28 UTC, stormcloud266 commented on api/src/lib/web3/check-function-call.ts
> +    const res = await fetch(url.toString())
It gives a TS error with node-fetch

![Screenshot 2023-03-27 at 10 27 32 AM](https://user-images.githubusercontent.com/19338130/228004284-f7af20bc-3e9e-4ba4-8b2d-d7c655428cbb.png)

2023-03-27 16:29 UTC, stormcloud266 commented on api/src/lib/web3/check-function-call.ts
> +    const data: FunctionCallResData = await res.json()
When I remove this i get an `unknown type` error even with the parse. Wasn't sure how to handle it another way

![Screenshot 2023-03-27 at 10 28 34 AM](https://user-images.githubusercontent.com/19338130/228004698-4a149c1c-e57f-44cb-b251-5d3c28cc5b62.png)

2023-03-27 16:42 UTC, stormcloud266 commented on api/src/lib/web3/check-function-call.ts
> +    const res = await fetch(url.toString())
Says it's fixed in 3.3.1, but I just updated and still get that error

https://github.com/node-fetch/node-fetch/issues/1261

2023-03-27 16:46 UTC, stormcloud266 commented on api/src/services/stepFunctionCalls/stepFunctionCalls.ts
> +export const StepFunctionCall: StepFunctionCallRelationResolvers = {
That's just from the generated file and it looks like they are caps in all the step types

2023-03-27 17:38 UTC, stormcloud266 commented on api/src/lib/web3/check-function-call.ts
> +  url.searchParams.set('methodIds', methodIds.join(','))
So the way it's set up on Nest right now is to take a comma separated list `&methodsIds=thing1,thing2` but it looks super straight forward to change it to `&methodId=thing&methodId=otherThing` if that's the better play here

2023-03-27 17:57 UTC, illepic commented on api/src/lib/web3/check-function-call.ts
> +  url.searchParams.set('methodIds', methodIds.join(','))
Let's do that, where the same param can appear multiple times, since that's built into the `new URL()` searchParams method.

2023-03-28 16:34 UTC, illepic approved these changes

2023-03-28 16:35 UTC, merged