itsmekori/eng-835-backup-database
infinity-keys/ik-landing pull request #846
Opened 2023-04-14 21:33 UTC by IvySwing

2023-04-14 21:49 UTC, illepic requested changes

2023-04-14 21:49 UTC, illepic commented on packages/discord-dust-game-bot/index.js
> +global.CronJob = require('./database_backup/cron.js')
Take this out

2023-04-14 22:27 UTC, IvySwing commented on packages/discord-dust-game-bot/index.js
> +global.CronJob = require('./database_backup/cron.js')
done

2023-04-15 16:00 UTC, illepic approved these changes

2023-04-17 17:37 UTC, merged