ENG-919: implement-keyp-auth
infinity-keys/ik-landing pull request #875
Opened 2023-05-03 15:32 UTC by stormcloud266

- add user and oauth schema, migrate
- begin file move
- use db auth, save user to db on login
- update logs
- update currentUser id to use authid
- move login/logout funcs
- upsert by email, add notes
- test client login functions

2023-05-09 16:31 UTC, illepic requested changes

2023-05-09 16:31 UTC, illepic commented on api/package.json
> +    "jsonwebtoken": "^9.0.0",
Important to note here that jose does exactly what jsonwebtoken does, there's no need for both. Flip out the jsonwebtoken code for the jose version.

2023-05-09 16:31 UTC, illepic commented on api/src/functions/auth.js
> +  logger.debug('Invoked /auth ')
Go ahead and log info about the user from `event` and `context` so we have logs we can search through. You can log like this: `logger.debug('Invoked /auth', { event, context })` or something similar. Augment all loggers with info that will help us sift through auth issues later.

2023-05-09 16:31 UTC, illepic commented on api/src/lib/keyp/oAuth/helpers.ts
> +export const encodeBody = (body) =>
This is literally what `new URL()` does: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set. I'm aware there's some difference https://stackoverflow.com/a/62969380

2023-05-09 16:31 UTC, illepic commented on api/src/lib/keyp/oAuth/oAuth.ts
> +    if (!Object.values(types).includes(type))
Would be awesome if `types` was an enum/union so we can benefit from other type stuff.

2023-05-09 16:31 UTC, illepic commented on api/src/lib/keyp/oAuth/oAuth.ts
> +    Object.keys(params).map((key) => {
Use `Object.entries()` instead.

2023-05-09 16:31 UTC, illepic commented on api/src/lib/keyp/oAuth/oAuth.ts
> +              id: userId,
Noting here that sometimes `userId` will be undefined. Do you still want to do this connect when userId is undefined?

2023-05-09 16:31 UTC, illepic commented on api/src/lib/keyp/oAuth/oAuth.ts
> +    logger.debug({ custom: tokens }, 'onSubmitCode() response')
Log `_accountId` with this stuff

2023-05-09 16:31 UTC, illepic commented on api/src/lib/keyp/oAuth/providers/index.ts
> +}
Let's talk about this one.

2023-05-09 16:31 UTC, illepic commented on api/src/lib/keyp/oAuth/providers/keyp/keyp.ts
> +import { JwtPayload, decode as decodeJwt } from 'jsonwebtoken'
This is where we can swap out for `jose`.

2023-05-09 16:31 UTC, illepic commented on api/src/lib/keyp/oAuth/providers/keyp/keyp.ts
> +if (process.env.LOCAL_KEYP_SERVER) KEYP_OAUTH_DOMAIN = 'http://localhost/oauth' // Don't worry about this, its only needed by the Keyp team
```ts
const KEYP_OAUTH_DOMAIN = process.env.LOCAL_KEYP_SERVER ? 'http://localhost/oauth' : 'https://app.usekeyp.com/oauth'
```

2023-05-09 16:31 UTC, illepic commented on api/src/lib/keyp/oAuth/providers/keyp/keyp.ts
> +    logger.debug({ custom: body }, '/token request body')
Does the order of the args to `logger.debug()` matter? If you sent in the arbitrary data, is it first or second?

2023-05-09 16:31 UTC, illepic commented on packages/contracts/src/index.ts
> +export { default as balanceOf1155 } from '../src/balanceOf1155.json'
Why is only this moved to src, but not the other?

2023-05-09 16:31 UTC, illepic commented on web/src/App.tsx
> +}
wat do

2023-05-09 16:31 UTC, illepic commented on web/src/Routes.tsx
> +      <AllContextProviders>
Well this is cool. I want to know more about this.

2023-05-09 16:31 UTC, illepic commented on web/src/components/LoginModal/LoginModal.tsx
> +      login_provider = `&login_provider=${type.split('KEYP_')[1]}`
`new URL()` with `.setParam()`

2023-05-09 16:31 UTC, illepic commented on web/src/providers/redirection/redirection.js
> +  }
Let's useState and useCallback for this stuff

2023-05-09 16:31 UTC, illepic commented on web/src/providers/redirection/redirection.js
Let's actually clean this up.

2023-05-09 16:31 UTC, illepic commented on web/src/providers/toast/toast.js
I'll let you deal with Toast.

2023-05-09 16:31 UTC, illepic commented on web/src/utils/helpers.js
> +  const errorText = typeof error === 'string' ? error : error.message
Also use `error instanceof Error` to check for error object (that has .message key)

2023-05-09 16:31 UTC, illepic commented on web/src/utils/popupLoadingHtml.js
y tho

2023-05-09 19:49 UTC, stormcloud266 commented on api/src/lib/keyp/oAuth/providers/keyp/keyp.ts
> +    logger.debug({ custom: body }, '/token request body')
it doesn't seem to matter

https://redwoodjs.com/docs/logger#quick-start

2023-05-09 19:53 UTC, stormcloud266 commented on api/src/lib/keyp/oAuth/oAuth.ts
> +              id: userId,
I believe when userId is undefined, it should spread the empty object. It's ben updated to do that. So if it's undefined the connection won't be made

2023-05-10 16:52 UTC, stormcloud266 commented on api/src/lib/keyp/oAuth/helpers.ts
> +export const encodeBody = (body) =>
This function is only used for the body and not the searchParams

2023-05-11 16:46 UTC, illepic approved these changes

2023-05-11 16:46 UTC, illepic commented on api/src/functions/auth.js
> +/* eslint-disable-next-line no-unused-vars */
Remove this line

2023-05-11 16:46 UTC, illepic commented on api/src/functions/auth.js
> +    if (!code || !state) throw 'logIn() Code or state not provided.'
Move this above `validateLoginRequest`

2023-05-11 16:46 UTC, illepic commented on api/src/lib/keyp/oAuth/oAuth.ts
> +    })
Let's move this somewhere that's not right in the middle of a bunch of runtime logic

2023-05-11 16:46 UTC, illepic commented on api/src/lib/keyp/oAuth/providers/keyp/keyp.ts
> +      idTokenExpiration: new Date(decoded.exp * 1000),
Throw if now `exp`

2023-05-11 16:46 UTC, illepic commented on api/src/lib/keyp/oAuth/providers/keyp/keyp.ts
> +const KEYP_OAUTH_DOMAIN = process.env.LOCAL_KEYP_SERVER
I do not have this .env var

2023-05-11 16:46 UTC, illepic commented on api/src/lib/keyp/oAuth/providers/keyp/keyp.ts
> +const KEYP_OAUTH_DOMAIN = process.env.LOCAL_KEYP_SERVER
Just set to https://app.usekeyp.com/oauth

2023-05-11 16:46 UTC, illepic commented on web/src/components/LoginModal/LoginModal.tsx
> +      window.location.href = url.toString()
Use the redwood way for forwarding/routing to forward, check if there are redwood params to this func to overwrite history.

2023-05-11 16:46 UTC, illepic commented on web/src/components/LoginModal/LoginModal.tsx
> +      window.location.href = url.toString()
https://redwoodjs.com/docs/router

2023-05-11 16:46 UTC, illepic commented on web/src/providers/index.tsx
> +      <RedirectionProvider>{children}</RedirectionProvider>
children on separate line

2023-05-11 16:46 UTC, illepic commented on web/src/providers/redirection/redirection.tsx
> +    type?: string | null
Make keys required, but keep `| null`

2023-05-11 16:46 UTC, illepic commented on web/src/utils/helpers.js
Let's make this guy ts

2023-05-11 16:46 UTC, illepic commented on web/src/utils/helpers.js
> +      : `Error auth ${functionName}()`
Take this out, change implementation to `e instanceof Error`

2023-05-11 17:21 UTC, stormcloud266 commented on web/src/components/LoginModal/LoginModal.tsx
> +      window.location.href = url.toString()
@illepic  since this is hitting an external link outside of redwood we can't use `navigate` here

2023-05-11 17:25 UTC, stormcloud266 commented on web/src/providers/index.tsx
> +      <RedirectionProvider>{children}</RedirectionProvider>
prettier isn't letting this happen...

2023-05-11 17:46 UTC, stormcloud266 commented on web/src/utils/helpers.js
This only ever formats a string, so I'm just chucking it.

2023-05-12 03:37 UTC, illepic requested changes
Last TINY thing, I swear! So close.

2023-05-12 03:37 UTC, illepic commented on web/src/providers/redirection/redirection.tsx
> +  }, [authState])
Yoooo, didn't catch this before: we need exhaustive deps (all vars listed in this array that are used within useEffect). Remove the eslint-disable line.

2023-05-12 13:49 UTC, stormcloud266 commented on web/src/providers/redirection/redirection.tsx
> +  }, [authState])
the deps have been exhausted, and the other function in there is now a usecallback

2023-05-12 15:14 UTC, illepic approved these changes

2023-05-12 15:16 UTC, merged