Ts fixes
infinity-keys/ik-landing pull request #880
Opened 2023-05-10 03:26 UTC by Richard-Burd

This is an attempt to fix typescript linting errors that are simple fixes.

2023-05-10 15:55 UTC, stormcloud266 requested changes

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/services/nfts-custom/nfts-custom.ts
> +  ) => {
This is an older service we created and it actually doesn't need to be a service since it's never called using graphql. Let's move this into the `lib` folder and update the import inside the `metadata` function file (you won't need the `QueryResolvers['nftByContractAndTokenId']` type at that point)

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/services/ik/submissions-custom/submissions-custom.ts
> +// the MutationResolvers type?  I don't see it in `api/types/graphql.d.ts`
This was for a function we aren't using anymore. If it's giving you an error we can comment out the file

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/lib/auth.ts
> +  { token }: { token: string }
There is a `Decoded` type in redwood

```
import { Decoded } from '@redwoodjs/api'
```

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/functions/discord-vote-bot.ts
> +import { APIGatewayProxyEventV2 } from 'aws-lambda'
Let's make this the `APIGatewayEvent` like other functions

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/functions/discord-mint-bot.ts
> +}) => {
Let's set event to `APIGatewayEvent`

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/functions/discord-mint-bot.ts
> +    }
Instead of returning an error if there's no image, let's update the `setThumbnail` to use a default image (maybe the small logo used elsewhere in this file) if `image` doesn't exist

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/functions/alpha-holders.ts
> +  if (!('tokenId' in event.queryStringParameters)) return { statusCode: 400 }
This`'tokenId' in` check is cool. I think we don't need line 19 if we have line 20

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/functions/alpha-holders.ts
> +    chain: string | number,
I believe all the `chain` params in the file can be set to `EvmChain`

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/functions/anonAttempt/anonAttempt.ts
> +  const { attempt } = JSON.parse(event.body?.toString() ?? '')
This works perfectly, but I'm thinking we should just return at the top if there is no body

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/functions/discord-vote-bot.ts
> +  const { body = '', headers } = event
Same deal here. Let's just return if there's no body

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/lib/auth.ts
> +  )
This was my mistake, and I found it on the PR I'm on right now. We can put this function back the way it was before, but at the top there is a `RedwoodUser` type, and its roles property should be `SiteRoles` not a string

```
type RedwoodUser = Record<string, unknown> & { roles?: string[] }
```

becomes

```
type RedwoodUser = Record<string, unknown> & { roles?: SiteRole[] }
```

That line was autogenerated and I had missed it earlier.

2023-05-10 15:55 UTC, stormcloud266 commented on api/src/services/userRewards/userRewards.ts
> +  })
instead of using `as` here, let's put another check in the `if` statement

```ts
if (!context.currentUser || context.currentUser.id !== string) return []
```

2023-05-10 19:01 UTC, Richard-Burd commented on api/src/functions/alpha-holders.ts
> +  if (!('tokenId' in event.queryStringParameters)) return { statusCode: 400 }
Without line 19, we'll get another linting error (on line 20) [I think] because TypeScript is not sure if `queryStringParameters` is defined or not.

I can add the optional chaining operator to tell TypeScript to only try accessing `tokenId` if `queryStringParameters` is defined, and if it is `undefined` or `null` - typescript will just `return undefined` and won't throw an error:

**`if (!event.queryStringParameters?.tokenId) return { statusCode: 400 }`**

This removes the linting error.

2023-05-10 19:58 UTC, Richard-Burd commented on api/src/services/userRewards/userRewards.ts
> +  })
This gives me a linting error on `string` - I think this is because TypeScript will consider this a type...and not a value.  If we want to avoid using `as` (which forces a type assertion without any type safety checks) we can do this:

```
export const userRewards: QueryResolvers['userRewards'] = () => {
  if (!context.currentUser || typeof context.currentUser.id !== 'string')
    return []

  return db.userReward.findMany({
    where: { userId: context.currentUser.id },
  })
}
```

2023-05-10 20:51 UTC, stormcloud266 requested changes

2023-05-10 20:51 UTC, stormcloud266 commented on api/src/lib/auth.ts
> +  decoded: Decoded | null,
Decoded itself accounts for the `null` state, so the `| null` can be removed here

2023-05-10 20:51 UTC, stormcloud266 commented on api/src/functions/discord-mint-bot.ts
> +    }
This can go now that we are using a ternary below

2023-05-10 20:51 UTC, stormcloud266 commented on api/src/functions/anonAttempt/anonAttempt.ts
> +  const { attempt } = JSON.parse(event.body.toString())
I don't think we need the `toString()` here

2023-05-10 20:51 UTC, stormcloud266 commented on api/src/functions/discord-mint-bot.ts
> +  const parsedBody = await JSON.parse(body || '')
Let's add the same code like you have it in anonAttempt. Then we can remove the `|| ''`

```
if (!event.body) {
    logger.info('/discord-mint-bot called without body')
    return { statusCode: 400 }
  }
```

2023-05-10 20:51 UTC, stormcloud266 commented on api/src/functions/discord-vote-bot.ts
> +  const parsedBody = await JSON.parse(body || '')
Should be able to remove `|| ''` here as well, now that we are checking it exists above

2023-05-10 20:51 UTC, stormcloud266 commented on api/src/lib/auth.ts
> +  )
Looks like we still need this one. Ping me if you want to go over this one

2023-05-10 20:56 UTC, stormcloud266 commented on api/src/services/userRewards/userRewards.ts
> +  })
Yes I definitely missed the `typeof` there. Good catch

2023-05-10 21:07 UTC, stormcloud266 commented on api/src/functions/alpha-holders.ts
> +    chain: string | number,
EvmChain here as well

2023-05-11 15:36 UTC, illepic approved these changes

2023-05-11 15:36 UTC, illepic commented on api/src/functions/discord-vote-bot.ts
> +      .setColor('#101d42')
Remove string, make it `0x101d42`

2023-05-11 15:40 UTC, illepic approved these changes

2023-05-11 15:40 UTC, stormcloud266 approved these changes

2023-05-11 15:48 UTC, merged