various linting fixes
infinity-keys/ik-landing pull request #904
Opened 2023-05-25 06:12 UTC by Richard-Burd

2023-05-25 14:58 UTC, stormcloud266 requested changes

2023-05-25 14:58 UTC, stormcloud266 commented on api/src/directives/requireAuth/requireAuth.ts
>  type RequireAuthValidate = ValidatorDirectiveFunc<{ roles?: string[] }>
I believe changing the roles typing here to `SiteRole[]` will let you undo the changes to `src/lib/auth`

2023-05-26 16:29 UTC, illepic requested changes

2023-05-26 16:29 UTC, illepic commented on api/src/lib/keyp/oAuth/helpers.ts
> +export const encodeBody = (body: Record<string, unknown>): string =>
`(body: Record<string, string>): string`

2023-05-26 16:29 UTC, illepic commented on api/src/lib/verifySignature.ts
```ts
if (!wallet) throw new Error('Wallet failed to initialize.');
```

place before 

```ts
const contractAddress = contractAddressLookup[chainId]
```

2023-05-26 16:29 UTC, illepic commented on api/src/services/submissions/submissions.scenarios.ts
Revert this file, ignore all scenarios.

2023-05-30 15:17 UTC, illepic approved these changes

2023-05-30 15:58 UTC, stormcloud266 approved these changes

2023-05-30 17:21 UTC, merged