new form epic
infinity-keys/ik-landing pull request #951
Opened 2023-07-07 00:29 UTC by Richard-Burd

2023-07-07 15:58 UTC, illepic approved these changes

2023-07-07 15:58 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +  update: (index: number, data: any) => void
`data` here will be https://github.com/infinity-keys/ik-landing/blob/rick/new-form-pages/api/db/schema.prisma#L394-L397

2023-07-07 15:58 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +const fieldArrayName = 'array'
`const nftsFieldArrayName = 'nftsArray`

2023-07-07 15:58 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +  const { control } = useForm()
```
const { control } = useForm<PuzzleFormType>()
```

2023-07-07 15:58 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +
```ts
type PuzzleFormType = {
  name: string;
  slug: string;
  // Other root fields
  // Need array of NFTs
  // Need array of Steps
}
```

2023-07-17 15:36 UTC, illepic requested changes

2023-07-17 15:36 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +type StepTypeData = SimpleText | NftCheck
Move all types down to where they are used.

2023-07-17 15:36 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +      <DisplayStepType stepType={data.stepType} data={data as StepTypeData} />
No `as` here, we'll fix together.

2023-07-17 15:36 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +const DisplayStepType: React.FC<DisplayStepTypeProps> = ({
No `React.FC`

2023-07-17 15:36 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +  console.log('Rendering DisplayStepType', stepType, data)
We'll remove log for prod.

2023-07-17 15:36 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +          Solution: {(data as SimpleText).solution}
We'll do something else besides `as`.

2023-07-17 15:36 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +  if (!data?.failMessage) return null
Toss a comment on here about why we're ejecting if there's NO `failMessage`.

2023-07-17 15:36 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +  const formMethods = useForm<Step>({
```ts
const { register } = useForm<Step>({
```

2023-07-17 15:36 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +  const { register } = formMethods
Same destructuring as above.

2023-07-17 15:36 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +          {...register(`failMessage`, { required: true })}
Try this without `register`, but with `name`. Let's see if these can be simplified.

2023-07-17 15:36 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +                e.target.value as 'SIMPLE_TEXT' | 'NFT_CHECK' | undefined
No `as`.

2023-07-17 15:36 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +
Feel free to remove carriage return between `Label` and form field.

2023-07-18 15:26 UTC, illepic requested changes

2023-07-18 15:26 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +  const data = useWatch({
Call this var `stepsField`

2023-07-18 15:26 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +        {...register('solution', { required: true })}
I don't think we need `{..register()}`, try the vanilla way.

2023-07-18 15:26 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +        {...register('contractAddress', { required: true })}
Let's try taking these `register`s off as well

2023-07-18 15:26 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +    <div className="nft-check">
Make this `Form formMethods={formMethods}`

2023-07-18 15:26 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +    <div className="my-4 max-w-3xl border-2 border-zinc-500 bg-zinc-300 p-4">
Make `Form` here too.

2023-07-18 17:02 UTC, Richard-Burd commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
> +        {...register('solution', { required: true })}
I tried this but it would not work:

```
const EditSimpleText = ({ value }: { value: Step }) => {
  const formMethods = useForm<Step>({
    defaultValues: value,
  })

  return (
    <Form formMethods={formMethods}>
      <div className="simple-text">
        <Label
          name="solution"
          className="rw-label"
          errorClassName="rw-label rw-label-error"
        >
          Solution
        </Label>
        <TextField 
          name="solution" 
          className="w-full" 
          placeholder="Solution"
        />
      </div>
    </Form>
  )
}
```

2023-10-10 16:08 UTC, illepic approved these changes

2023-10-10 16:08 UTC, illepic commented on web/src/pages/FormArchetypePage/FormArchetypePage.tsx
> +}
Bring these types in from `web/types/graphql.d.ts`. As much as we can.

2023-10-10 16:08 UTC, illepic commented on web/src/pages/FormArchetypePage/FormArchetypePage.tsx
> +        <TextField
For all textfields that have placeholders, use the tailwind placeholder class instead of custom CSS (from index.css).

2023-10-10 16:08 UTC, illepic commented on web/src/pages/FormArchetypePage/FormArchetypePage.tsx
> +    console.log(input)
Can probably nuke this/comment this out for prod.

2023-10-10 16:08 UTC, illepic commented on web/src/pages/FormArchetypePage/FormArchetypePage.tsx
> +      alert(`Rewardable created via Burd's Form!`)
Can nuke this also when live.

2023-10-10 16:08 UTC, illepic commented on web/src/pages/PuzzleCreatePage/PuzzleCreatePage.tsx
This is the old form page, we'll nuke later.

2024-02-20 16:45 UTC, merged